llamafolio/llamafolio-api

src/adapters/aave-v3/index.ts
src/adapters/aave-v3/optimism/index.ts

Add Optimism on Aave-v3 adapter
`pnpm run adapter-balances aave-v3 optimism 0x4ecb5300d9ec6bca09d66bfd8dcb532e3192dda1`
`pnpm run adapter-balances aave-v3 optimism 0x2e003a06c5b0244f2eaded5bdf9052398d23cbe4`

Feat: Adapter Aave-v3 - Optimism

---

src/adapters/compound-v3/arbitrum/index.ts
src/adapters/compound-v3/index.ts
src/adapters/compound-v3/polygon/index.ts

Add Compound-v3 on both polygon + arbitrum chains
`pnpm run adapter-balances compound-v3 arbitrum 0x711298ad03242cc206f0b46fd8894251f47f481f`
`pnpm run adapter-balances compound-v3 arbitrum 0xcc529ebfee1257eaa43a1d19d5cdc7bf57a30193`
`pnpm run adapter-balances compound-v3 arbitrum 0xef819443b1cbd55ab0b137f644fffa8ebb4208ee`
`pnpm run adapter-balances compound-v3 arbitrum 0x4b2cf5c94a88934870b523983b22e6d2dd1b6577`

Feat: Adapter, Compound-v3 - (Arbitrum)-(Polygon)

---

src/adapters/crvusd/ethereum/index.ts
src/adapters/crvusd/index.ts

crvusd adapters added

---

package.json
pnpm-lock.yaml

bump: llamafolio-tokens 0.1.67

---

src/adapters/convex-finance/ethereum/pool.ts

Small fix, there were 2 different CVX
`pnpm run adapter-balances convex-finance ethereum 0xbdfa4f4492dd7b7cf211209c4791af8d52bf5c50`
`pnpm run adapter-balances convex-finance ethereum 0xbdfa4f4492dd7b7cf211209c4791af8d52bf5c50`

Fix: Adapter, Convex-Finance 

---

src/lib/geist/stake.ts

it was showing the staking contract (MultiFeeDistribution) instead of the staking token

fix: geist staking

---

src/adapters/lybra-finance/ethereum/vest.ts

Fix returned wrong address on vest logic

Fix: Adapter Lybra-finance

---

package.json
pnpm-lock.yaml

bump: llamafolio-tokens 0.1.69

---

src/adapters/wallet/index.ts

fix: wallet adapter native flag

---

.vscode/launch.json
scripts/build-adapters.ts
scripts/revalidate-contracts-rec.ts
scripts/revalidate-contracts.ts
src/db/tokens.ts

fix a Postgres issue dealing with `\x00` in token symbols

fix: insert tokens symbol

---

src/handlers/getToken.ts

fetch on-chain info instead of just using tokens from `llamafolio-tokens`

feat: token endpoint fetch missing onchain info

---

package.json
pnpm-lock.yaml

bump: llamafolio-tokens 0.1.71

---

src/adapters/synthetix/ethereum/index.ts
src/adapters/synthetix/optimism/index.ts

fix: synthetix borrow underlying

---

.vscode/launch.json
src/adapters/gravita-protocol/ethereum/index.ts
src/adapters/gravita-protocol/ethereum/lend.ts
src/adapters/gravita-protocol/ethereum/stake.ts
src/adapters/gravita-protocol/index.ts
src/adapters/index.ts

Add Gravita-protocol (stake+lend)
`pnpm run adapter-balances gravita-protocol ethereum 0xbdfa4f4492dd7b7cf211209c4791af8d52bf5c50`
`pnpm run adapter-balances gravita-protocol ethereum 0x6e96a8f5493d55c3a5cdbf2b2d8e049f812a929a`

Feat: Adapter, Gravita-protocol

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/sherlock/ethereum/farm.ts
src/adapters/sherlock/ethereum/index.ts
src/adapters/sherlock/index.ts

`pnpm run adapter-balances sherlock ethereum 0xbdfa4f4492dd7b7cf211209c4791af8d52bf5c50`
`pnpm run adapter-balances sherlock ethereum 0x6a04941de896e4215eeb8e6eb1b72ad2904d2402`

Feat: Adapter, Sherlock 

---

src/adapters/abracadabra/arbitrum/index.ts
src/adapters/abracadabra/ethereum/index.ts
src/adapters/abracadabra/fantom/index.ts

Add some missing contracts on Abracadabra adapter
`pnpm run adapter-balances abracadabra ethereum 0x7a16ff8270133f063aab6c9977183d9e72835428`

Feat: Adapter, Abracadabra

---

scripts/update-tokens.ts
src/lib/chains.ts
src/lib/erc20.ts
src/lib/multicall.ts
src/lib/providers/viem.ts

fixed update-tokens script and adapter wallet

---

src/lib/multicall.ts
src/lib/providers/chains.ts
src/lib/providers/viem.ts

fix: multicall config

---

src/adapters/crvusd/ethereum/balance.ts
src/adapters/crvusd/ethereum/contract.ts
src/adapters/crvusd/ethereum/index.ts

`pnpm run adapter-balances crvusd ethereum 0x425d16b0e08a28a3ff9e4404ae99d78c0a076c5a`
==================================================================================
`pnpm run adapter-balances crvusd ethereum 0x425d16b0e08a28a3ff9e4404ae99d78c0a076c5a`

Fix: crvUSD interaction issues

---

.vscode/launch.json
src/adapters/belt-finance/bsc/contract.ts
src/adapters/belt-finance/bsc/farm.ts
src/adapters/belt-finance/bsc/index.ts
src/adapters/belt-finance/bsc/lp.ts
src/adapters/belt-finance/bsc/stake.ts
src/adapters/belt-finance/index.ts
src/adapters/index.ts

`pnpm run adapter-balances belt-finance bsc 0xa9ff08af55b24bb5d064d776a078e8a292b8dfe2`
`pnpm run adapter-balances belt-finance bsc 0x7341579c04ae64acdb116f1afc7ce26076090f68`
`SingleUnderlyings`
`pnpm run adapter-balances belt-finance bsc 0xabf0cdd827ab1902213269fc4427c3a8655e60c2`
_SwapUnderlyings_
`pnpm run adapter-balances belt-finance bsc 0xa9ff08af55b24bb5d064d776a078e8a292b8dfe2`
_FourBeltUnderlyings_
`pnpm run adapter-balances belt-finance bsc 0x25b86d36dc4d9d09d41415daf31ba7ffa7143f35`

Feat: Adapter, Belt-Finance, (stake, farm, lp)

---

package.json
pnpm-lock.yaml
src/adapters/1inch-network/common/stake.ts
src/adapters/aave-v3/common/lending.ts
src/adapters/arrakis/common/balances.ts
src/adapters/bancor-v3/ethereum/pools.ts
src/adapters/binance-staked-eth/bsc/index.ts
src/adapters/binance-staked-eth/ethereum/index.ts
src/adapters/creth2/ethereum/index.ts
src/adapters/euler/ethereum/index.ts
src/adapters/gnosis-protocol-v1/ethereum/index.ts
src/adapters/homora-v2/common/balance.ts
src/adapters/liqee/common/balance.ts
src/adapters/nodedao/ethereum/index.ts
src/adapters/platypus-finance/avalanche/index.ts
src/adapters/stafi/ethereum/index.ts
src/adapters/stakehound/ethereum/index.ts
src/adapters/the-open-dao-sos/ethereum/balance.ts
src/adapters/wallet/index.ts
src/lib/aave/v2/lending.ts
src/lib/balance.ts
src/lib/chains.ts
src/lib/compound/v2/lending.ts
src/lib/erc20.ts
src/lib/pools.ts
src/lib/price.ts
src/lib/stake.ts
src/lib/uniswap/v2/pair.ts

- define `nativeCurrency` directly in chains config (as viem)
- remove `coingeckoId` reference
- remove `llamafolio-tokens` `native` and `wallet` references (all tokens present in llamafolio-tokens belong to the wallet adapter)
- use `ERC20#balanceOf` calls instead of MultiCoinLookupContract as error handling is done on a per-cal basis

feat: update llamafolio-tokens

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/raft/ethereum/balance.ts
src/adapters/raft/ethereum/contract.ts
src/adapters/raft/ethereum/index.ts
src/adapters/raft/index.ts

Add Raft adapter (lend/borrow)
`pnpm run adapter-balances raft ethereum 0x35e3564c86bc0b5548a3be3a9a1e71eb1455fad2`
`pnpm run adapter-balances raft ethereum 0x9026a229b535ecf0162dfe48fdeb3c75f7b2a7ae`

Feat: Adapter Raft

---

src/adapters/conic-finance/ethereum/index.ts

Update: stakers contracts on CNC adapter

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/ipor/ethereum/farm.ts
src/adapters/ipor/ethereum/index.ts
src/adapters/ipor/ethereum/lp.ts
src/adapters/ipor/ethereum/stake.ts
src/adapters/ipor/index.ts

`pnpm run adapter-balances ipor ethereum 0xb7b9fad3ce7b370a473510d629a1716c59f752b7`
`pnpm run adapter-balances ipor ethereum 0x7bfee91193d9df2ac0bfe90191d40f23c773c060`
`pnpm run adapter-balances ipor ethereum 0x9c7689d597869665816d453219615eaa10536005`

Feat: Adapter, Ipor

---

package.json

I was getting these errors
```
Usage Error: Unsupported package manager specification (>=pnpm@8.0.0,>=pnpm,8.0.0)
$ pnpm ...
```

fix: packageManager option

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/silo-finance/arbitrum/index.ts
src/adapters/silo-finance/common/balance.ts
src/adapters/silo-finance/common/pool.ts
src/adapters/silo-finance/ethereum/index.ts
src/adapters/silo-finance/index.ts

Add Silo-Finance on both ethereum + arbitrum
`pnpm run adapter-balances silo-finance ethereum 0x26e4e986f70cf37078dd0a8a1ee245a3aedce4d9`
`pnpm run adapter-balances silo-finance ethereum 0xd3a9dccb4cfd983ff69e688ddb6491e010301b7a`
`pnpm run adapter-balances silo-finance ethereum 0x7a16ff8270133f063aab6c9977183d9e72835428`
`pnpm run adapter-balances silo-finance arbitrum 0x0330414bbf9491445c102a2a8a14adb9b6a25384`
`pnpm run adapter-balances silo-finance arbitrum 0xaae8c50d76c76fb8947c9a203103d28b55862977`

Feat : Adapter Silo-Finance

---

.github/workflows/ci.yml
.github/workflows/test.yml
test/routes.sh

Related: #702 
Simple `curl` checks to run in CI. CI fails if any of the curls fails.

feat: test endpoints with simple curl

---

src/lib/chains.ts
src/lib/providers/index.ts
src/lib/providers/viem.ts

RPC endpoints have different batch size limit, add a parameter to adjust those.
Error:
```
docsPath: undefined,
metaMessages: undefined,
shortMessage: 'An error occurred while executing: RPC Request failed.\n' +
'\n' +
'URL: https://bsc-dataseed.binance.org/\n' +
'Request body: {"method":"eth_call","params":...,"latest"]}\n' +
'\n' +
'Details: batch length does not support more than 100\n' +
'Version: viem@1.2.6',
version: 'viem@1.2.6',
cause: [RpcRequestError]
```

feat: http transport configs

---

src/adapters/wallet/index.ts
src/lib/chains.ts

Disable Transfer interactions for the wallet adapter, instead use all tokens from our llamafolio-tokens directory

feat: wallet adapter check all tokens

---

src/handlers/updateBalances.ts

always run wallet adapter on each chain (even if there's no interaction at all, this might happen if the user received some gas token but never used the chain for instance)

feat: run wallet adapter if no interaction

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/pearlfi/index.ts
src/adapters/pearlfi/polygon/farm.ts
src/adapters/pearlfi/polygon/index.ts

`pnpm run adapter pearlfi polygon 0xf4d40a328cb2320c94f009e936f840d2d8931721`
`pnpm run adapter pearlfi polygon 0xb02b5d046c37301f0cf5caa25c3a437314ce2fd0`
`pnpm run adapter pearlfi polygon 0xd9a05487a8736a6c6bfc379c599a7399008f4ea9`
`pnpm run adapter pearlfi polygon 0xb77ec71c90a533719df75bc6a209f7fb3e936eed`
`pnpm run adapter pearlfi polygon 0x5d77ef27dc3c04f51c4e834ee2881cac963926f1`

feat: Adapter Pearl-Finance

---

package.json
pnpm-lock.yaml
src/db/contracts.ts
src/handlers/getToken.ts

Find token in protocols definitions and add underlying details if available: ERC20 details, price, pool supply, LP token price.
If token appears in multiple protocols, this will do a best-effort match between underlyings (if different protocols indicate  different underlyings, there may be something wrong)
```bash
curl -G http://localhost:3000/tokens/ethereum/0x00ad8ebf64f141f1c81e9f8f792d3d1631c6c684 | jq
```
```json
{
"chain": "ethereum",
"address": "0x00ad8ebf64f141f1c81e9f8f792d3d1631c6c684",
"category": "borrow",
"symbol": "variableDebtCRV",
"decimals": 18,
"adapterId": "aave-v2",
"totalSupply": "36275025661724000240762766",
"underlyings": [
{
"chain": "ethereum",
"address": "0xd533a949740bb3306d119cc777fa900ba034cd52",
"name": "CurveDAOToken",
"decimals": 18,
"symbol": "CRV"
}
]
} …
```

[WIP] feat: get token underlyings details

---

.github/workflows/test.yml
test/routes.sh

fix: only log errors in routes test

---

.github/workflows/refresh-r2.yml

fix: temp dir location in ci

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/woofi/arbitrum/index.ts
src/adapters/woofi/avalanche/index.ts
src/adapters/woofi/bsc/index.ts
src/adapters/woofi/common/contract.ts
src/adapters/woofi/common/farm.ts
src/adapters/woofi/common/stake.ts
src/adapters/woofi/ethereum/index.ts
src/adapters/woofi/fantom/index.ts
src/adapters/woofi/index.ts
src/adapters/woofi/optimism/index.ts
src/adapters/woofi/polygon/index.ts

Add Woofi adapter
_Arbitrum_
`pnpm run adapter woofi arbitrum 0x60bcdb4c8c07033d99e71dbe29235848f750f321`
_Polygon_
`pnpm run adapter woofi polygon 0x91697beb0f8a061a1c7b1842a4a0b57decc5bd1d`
_BSC_
`pnpm run adapter woofi bsc 0x7ee05b0019858df33d14d36b2208ad8483d9eee1`
_Fantom_
`pnpm run adapter woofi fantom 0x743a87328003e3ef168f361eb442b841214d32a7`
_Optimism_
`pnpm run adapter woofi optimism 0xa2ebd97892502847061fe611efd5e289dbfa0703`
_Ethereum_
`pnpm run adapter woofi ethereum 0x7eb520927aec1d02a463ee644a73ff99dbf293f1`
_Arbitrum_
`pnpm run adapter woofi arbitrum 0xc0f8c29e3a9a7650a3f642e467d70087819926d6`
_Polygon_
`pnpm run adapter woofi polygon 0xc0f8c29e3a9a7650a3f642e467d70087819926d6`
_BSC_
`pnpm run adapter woofi bsc 0xc0f8c29e3a9a7650a3f642e467d70087819926d6`
_Fantom_
`pnpm …

feat: Adapter Woofi

---

.vscode/launch.json
src/adapters/extra-finance/index.ts
src/adapters/extra-finance/optimism/balance.ts
src/adapters/extra-finance/optimism/index.ts
src/adapters/extra-finance/optimism/pool.ts
src/adapters/extra-finance/optimism/vault.ts
src/adapters/index.ts

Extra-Finance (OP) Farm + Lock + [WIP] leveraged
`pnpm run adapter extra-finance optimism 0xa937f63ba1d69fd7e022fd50628b6d8fcfbde52d`
`pnpm run adapter extra-finance optimism 0x4be74aca4a0ab2da013d655390b492d816b2b335`
`pnpm run adapter extra-finance optimism 0x018c8a81cb02ca1a327baefd400f75f57ea57ba2`

feat: Adapter Extra-Finance

---

.vscode/launch.json
src/adapters/eigenlayer/ethereum/balance.ts
src/adapters/eigenlayer/ethereum/index.ts
src/adapters/eigenlayer/index.ts
src/adapters/index.ts

`pnpm run adapter eigenlayer ethereum 0x66b870ddf78c975af5cd8edc6de25eca81791de1`
`pnpm run adapter eigenlayer ethereum 0x578366e6327e9681c3fc02c47a2e88df9c8e02eb`

feat: Adapter, EigenLayer

---

.vscode/launch.json
src/adapters/florence-finance/ethereum/balance.ts
src/adapters/florence-finance/ethereum/index.ts
src/adapters/florence-finance/index.ts
src/adapters/index.ts

`pnpm run adapter-balances florence-finance ethereum 0x4807c267122c8a70829b18ccae2b855b454b50e5`
`pnpm run adapter-balances florence-finance ethereum 0x597d814d1c28f42355453744f1ea1f0f35b87981`

feat: Adater, Florence-Finance

---

.vscode/launch.json
src/adapters/cvault-finance/ethereum/contract.ts
src/adapters/cvault-finance/ethereum/farm.ts
src/adapters/cvault-finance/ethereum/index.ts
src/adapters/cvault-finance/ethereum/lend.ts
src/adapters/cvault-finance/index.ts
src/adapters/index.ts

`pnpm run adapter-balances cvault-finance ethereum 0x247c08e4f8add3f9e8890323325dd29543d1c285`
`pnpm run adapter-balances cvault-finance ethereum 0x2bb6d57cc4bc57e0b4e1e4478b1e963b0b214264`
`pnpm run adapter-balances cvault-finance ethereum 0x2f65768a403b8e1ae1743f846f1346766e61a41d`
`pnpm run adapter-balances cvault-finance ethereum 0xa88bea34c9b1d56681e72150d49238a23daad189`

feat: Adappter, CVault-Finance

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/reserve/ethereum/balance.ts
src/adapters/reserve/ethereum/index.ts
src/adapters/reserve/index.ts

`pnpm run adapter reserve ethereum 0xbff0113bfba0b74f8d1adeaa8e5f00d2bf96899c`
`pnpm run adapter reserve ethereum 0xc6625129c9df3314a4dd604845488f4ba62f9db8`

feat: Adapter, Reserve

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/linear-finance/bsc/balance.ts
src/adapters/linear-finance/bsc/index.ts
src/adapters/linear-finance/index.ts

`pnpm run adapter-balances linear-finance bsc 0xbb49a68c8ea9c2374082b738a7297c28ef3fda26`

feat: Adapter, Linear-Finance

---

package.json
pnpm-lock.yaml

bump: llamafolio-tokens 0.1.85

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/sphere-finance/index.ts
src/adapters/sphere-finance/polygon/index.ts

`pnpm run adapter sphere-finance polygon 0x77412737180e186361bf860660ab858ca7677c54`

feat: Adapter, Sphere-finance

---

src/handlers/updateBalances.ts
src/lib/balance.ts

fix: https://github.com/llamafolio/llamafolio-api/issues/755

fix: sanitize priced balances

---

src/handlers/getNFTs.ts
src/lib/nft/defillama.ts
src/lib/nft/quick-node.ts

use defillama nft collections data

---

src/handlers/getBalancesTokens.ts

feat: filter out token bals < 0.1 USD

---

src/handlers/getBalancesTokens.ts

up min value to 0.001

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/reflexer/ethereum/farm.ts
src/adapters/reflexer/ethereum/index.ts
src/adapters/reflexer/ethereum/stake.ts
src/adapters/reflexer/index.ts

`pnpm run adapter-balances reflexer ethereum 0x1f84ca2c0a406b32e083e4e41032fd148364df48`
`pnpm run adapter-balances reflexer ethereum 0xe207f98c7ad7f7b3895d4a105453e898771e2067`
`pnpm run adapter-balances reflexer ethereum 0xd1efb42da848fe7ba4c2017b96b7023bb6edd4ee`

feat: Adapter, Reflexer

---

.vscode/launch.json
src/adapters/ethos-reserve/index.ts
src/adapters/ethos-reserve/optimism/balance.ts
src/adapters/ethos-reserve/optimism/index.ts
src/adapters/index.ts

`pnpm run adapter ethos-reserve optimism 0xc2945ab7579b4c05def2cea0f404268fc75952a2`
`pnpm run adapter ethos-reserve optimism 0x11d67fa925877813b744abc0917900c2b1d6eb81`
`pnpm run adapter ethos-reserve optimism 0x82e8936b187d83fd6eb2b7dab5b19556e9deff1c`

feat: Adapter, Ethos-reserve

---

.vscode/launch.json
src/adapters/deltaprime/avalanche/balance.ts
src/adapters/deltaprime/avalanche/index.ts
src/adapters/deltaprime/avalanche/pool.ts
src/adapters/deltaprime/index.ts
src/adapters/index.ts

`pnpm run adapter deltaprime avalanche 0x70f795df58c9823fa494e284b481c66a39ad6140`
`pnpm run adapter deltaprime avalanche 0x2446beb3905cffbd2c5eb18f1f9c2996b05257c4`

feat: Adapter, DeltaPrime

---

src/adapters/stakewise/ethereum/index.ts
src/adapters/stakewise/gnosis/index.ts
src/adapters/stakewise/index.ts

Add Stakewise on Gnosis chain
`pnpm run adapter stakewise gnosis 0x411fa33f660edded5dddc57cd50ac33eb4684c6b`

feat: Adapter, Stakewise gnosis

---

src/adapters/curve-dex/common/balance.ts
src/adapters/curve-dex/common/pool.ts
src/adapters/curve-dex/gnosis/index.ts
src/adapters/curve-dex/index.ts
src/adapters/curve-dex/moonbeam/index.ts

Moonbeam
`pnpm run adapter curve-dex moonbeam 0x4efb9942e50ab8bba4953f71d8bebd7b2dcde657`
`pnpm run adapter curve-dex moonbeam 0xdbf828580b6881806c90808db04987b423722e74`
Gnosis
`pnpm run adapter curve-dex gnosis 0xd91770e868c7471a9585d1819143063a40c54d00`
`pnpm run adapter curve-dex gnosis 0x58950d34f2437e75d6dc9809c5b70429c721a05a`
OldChain
_Polygon_
`pnpm run adapter curve-dex polygon 0x989aeb4d175e16225e39e87d0d97a3360524ad80`
_Arbitrum_
`pnpm run adapter curve-dex arbitrum 0x989aeb4d175e16225e39e87d0d97a3360524ad80`

Add fix on Curve alt + handling error + add chains

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/magnate-finance/base/balance.ts
src/adapters/magnate-finance/base/index.ts
src/adapters/magnate-finance/index.ts

Add Magnate-finance (compound Fork)
`pnpm run adapter magnate-finance base 0xf6151e45299871003d2b47c10e7b6ca456f6fe0f`
`pnpm run adapter magnate-finance base 0x8cf877e91118ab50ff00de1e6e6a566c9c2b8228`

feat: Adapter, Magnate-finance

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/retro/index.ts
src/adapters/retro/polygon/balance.ts
src/adapters/retro/polygon/index.ts

Add Retro Adapter on Polygon chain
`pnpm run adapter retro polygon 0x41bc7d0687e6cea57fa26da78379dfdc5627c56d`
`pnpm run adapter retro polygon 0x193db18a5ef9a0320b7374c1fe8af976235f3211`

feat: Adapter, Retro

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/moonwell/base/index.ts
src/adapters/moonwell/common/market.ts
src/adapters/moonwell/index.ts
src/adapters/moonwell/moonbeam/index.ts

Add Moonwell on both Base & Moonbeam
`pnpm run adapter moonwell base 0x7780e86699e941254c8f4d9b7eb08ff7e96bbe10`
`pnpm run adapter moonwell base 0x87839e0378c62d8962c76726cfdd932a97ef626a`
`pnpm run adapter moonwell base 0x9e67663c01e86c7bd8c3cd2285c681dbad1c8327`
`pnpm run adapter moonwell base 0xb13b8a0744a06c1d0e59b297b1893619a4dc4017`
`pnpm run adapter moonwell base 0x1e7371aefd7943d29556ada3d34b4a5186a823a0`

feat: Adapter, Moonwell

---

src/adapters/arrakis/arbitrum/index.ts
src/adapters/arrakis/common/balances.ts
src/adapters/arrakis/common/contracts.ts
src/adapters/arrakis/ethereum/index.ts
src/adapters/arrakis/index.ts
src/adapters/arrakis/optimism/index.ts

Arbitrum
`pnpm run adapter arrakis arbitrum 0xcb58a1b3f04ed7cf1d341d4555f4e62b37c394e3`
`pnpm run adapter arrakis arbitrum 0xc78f036f557925270e3506e140cfe5f2a188c3a3`
`pnpm run adapter arrakis arbitrum 0x45f7093565b72e8fe5e97bc84d8f9919cc7ae15f`
Ethereum
`pnpm run adapter arrakis ethereum 0x70fce97d671e81080ca3ab4cc7a59aac2e117137`
Optimism
`pnpm run adapter arrakis optimism 0x738671901affbc417fa370cf936e461bb5315bd0`
Polygon
`pnpm run adapter arrakis polygon 0x071c8c14e17ee12b15de545860ac7cf0d4858417`

feat: Adapter, Arrakis, add arbitrum + farm logic @ll chains

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/overnight-finance/arbitrum/contract.ts
src/adapters/overnight-finance/arbitrum/index.ts
src/adapters/overnight-finance/base/contract.ts
src/adapters/overnight-finance/base/index.ts
src/adapters/overnight-finance/common/balance.ts
src/adapters/overnight-finance/index.ts
src/adapters/overnight-finance/optimism/contract.ts
src/adapters/overnight-finance/optimism/index.ts
src/adapters/overnight-finance/polygon/contract.ts
src/adapters/overnight-finance/polygon/index.ts

`pnpm run adapter overnight-finance base 0xbf409666d08cf66def64908b557efac58a57ef0e`
`pnpm run adapter overnight-finance polygon 0x9030d5c596d636eefc8f0ad7b2788ae7e9ef3d46`
`pnpm run adapter overnight-finance polygon 0x1bd3f2a045615c435f1e11aec650e80e3a24f71b`
`pnpm run adapter overnight-finance optimism 0x9030d5c596d636eefc8f0ad7b2788ae7e9ef3d46`
`pnpm run adapter overnight-finance optimism 0x14730014eea880f2d52ac0b67442c485242d9b9c`
`pnpm run adapter overnight-finance arbitrum 0x9030d5c596d636eefc8f0ad7b2788ae7e9ef3d46`

feat: Adapter, Overnight-finance

---

package.json
pnpm-lock.yaml
src/adapters/coinbase-wrapped-staked-eth/base/index.ts

feat: base tokens

---

src/db/balances.ts
src/handlers/getInfoAddress.ts

fix: info address active since query

---

src/db/contracts.ts

fix: adapters_contracts select by lowercased address

---

scripts/run-adapter.ts

fix: run adapter token resolver

---

src/handlers/updateBalances.ts

fix: update balances missing breakdown

---

src/db/adapters.ts

fix: latest protocols filter not fully integrated

---

src/adapters/rocket-pool/ethereum/index.ts

add missing contract rETH

---

src/adapters/crvusd/ethereum/contract.ts

> Removal of underlyings props which were not used by our contracts and which prevented the display of certain contracts

fix: Adapter crvUSD

---

.vscode/launch.json
src/adapters/alien-base/base/balance.ts
src/adapters/alien-base/base/index.ts
src/adapters/alien-base/index.ts
src/adapters/index.ts

LP
`pnpm run adapter-balances alien-base base 0x52eaecac2402633d98b95213d0b473e069d86590`
FARM
`pnpm run adapter-balances alien-base base 0xdd8bb6779d6d7a2540c38cae1e95c2a1c350a390`

feat: Adapter, Alien-Base

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/whiteheart/ethereum/balance.ts
src/adapters/whiteheart/ethereum/index.ts
src/adapters/whiteheart/index.ts

`pnpm run adapter whiteheart ethereum 0xe787deec0be77db98a1294193e2c1600c8a8687d`

feat: Adapter, whiteheart

---

scripts/nft-floors.ts

update: use mapped object for nft-floors r2

---

package.json
src/db/adapters.ts
src/db/protocols.ts
src/db/tokens.ts

fix: protocols remove optimize statement

---

src/db/balances.ts
src/handlers/updateBalances.ts

feat: balances table keep old

---

src/adapters/tangible/polygon/farm.ts
src/adapters/tangible/polygon/index.ts
src/adapters/tangible/polygon/stake.ts

> Add farming part + v2 staking
_/!\ Defillama Api doesnt show CVR price at the moment_
`pnpm run adapter tangible polygon 0x3baea49b71461deab46e6f42548d0005359ff629`
`pnpm run adapter tangible polygon 0xd1758fbabae91c805be76d56548a584ef68b81f0`
`pnpm run adapter tangible polygon 0xb02b5d046c37301f0cf5caa25c3a437314ce2fd0`

feat: Adapter, Tangible

---

scripts/revalidate-contracts.ts
src/db/adapters.ts
src/db/contracts.ts
src/handlers/revalidateAdapters.ts

feat: rm delete old adapters

---

src/db/adapters.ts
src/db/contracts.ts

fix: queries adapters final

---

src/handlers/getContracts.ts
src/handlers/getInfoAddress.ts

This data is immutable, it'll only change as we support more chains

feat: get info increase max-age

---

src/handlers/getLatestBalances.ts
src/handlers/updateBalances.ts

feat: get latest balances save DB call

---

package.json
pnpm-lock.yaml
src/adapters/wallet/index.ts
src/handlers/updateBalances.ts
src/lib/chains.ts
src/lib/providers/chains.ts

feat: update balances wallet use tokens received

---

scripts/nft-floors.ts

increase fetched collections count for floors to 100

---

src/adapters/wallet/index.ts

fix: wallet adapter indexed chains

---

scripts/update-yields.ts
src/db/balances.ts
src/db/yields.ts
src/handlers/getBalances.ts
src/handlers/getLatestBalances.ts
src/handlers/updateBalances.ts
src/handlers/updateYields.ts

feat: balances yields speed

---

src/db/clickhouse.ts

fix: prevent error if redefining bigint convertor

---

src/db/contracts.ts
src/handlers/getBalancesTokens.ts

fix: balances tokens use interactions

---

src/lib/chains.ts

feat: BSC LlamaNodes RPC

---

src/db/history.ts
src/handlers/getHistory.ts

fix: history api chain filter

---

src/adapters/sonne-finance/base/index.ts
src/adapters/sonne-finance/index.ts

`pnpm run adapter sonne-finance base 0x3e018a972ed429b01d11bda4d19e6902680104c8`
`pnpm run adapter sonne-finance base 0xc092f4d15d69ca9322899bf47358ccbc61bb9bce`

feat: Update Sonne finance --> Base

---

src/adapters/uniswap-v3/base/index.ts
src/adapters/uniswap-v3/bsc/index.ts
src/adapters/uniswap-v3/index.ts

`pnpm run adapter uniswap-v3 base 0xbbe6495f5de6805c3e28bd66b26ad2076c006dc8`
`pnpm run adapter uniswap-v3 base 0xccfa0530b9d52f970d1a2daea670ce58e4176389`
`pnpm run adapter uniswap-v3 bsc 0x8181bf635957e37aa25320b3299285bf942cd141`

feat: Update Uni-v3 --> Base + BSC

---

src/db/adapters.ts
src/db/balances.ts
src/db/contracts.ts
src/db/protocols.ts

feat: adapters_contracts force lowercase address + fix delete adapter

---

scripts/delete-adapter.ts
scripts/insert-llamafolio-tokens.ts
scripts/revalidate-contracts-rec.ts
scripts/revalidate-contracts.ts
scripts/run-adapter-balances.ts
scripts/update-balances.ts
scripts/update-protocols.ts
scripts/update-tokens.ts
scripts/update-yields.ts
src/db/clickhouse.ts
src/handlers/getAdapters.ts
src/handlers/getBalances.ts
src/handlers/getBalancesTokens.ts
src/handlers/getContracts.ts
src/handlers/getGasUsedChart.ts
src/handlers/getHistory.ts
src/handlers/getInfoAddress.ts
src/handlers/getInfoStats.ts
src/handlers/getLabels.ts
src/handlers/getLatestProtocols.ts
src/handlers/getLatestSnapshot.ts
src/handlers/getProtocols.ts
src/handlers/getSyncStatus.ts
src/handlers/getToken.ts
src/handlers/getTokenHolders.ts
src/handlers/revalidateAdapters.ts
src/handlers/updateProtocols.ts
src/handlers/updateYields.ts

Feat: DB client reuse TCP/IP connection

---

src/db/clickhouse.ts

fix: db conn import env

---

src/db/contracts.ts

feat: adapters contracts store underlyings array directly

---

src/db/balances.ts

Unwrapping underlyings was hiding some necessary info. We need to know exactly if the user is holding the token or the underlying

feat: rm unwrap underlyings

---

package.json
pnpm-lock.yaml

bump: viem 1.10.8

---

package.json
pnpm-lock.yaml
scripts/get-tokens.ts
src/lib/chains.ts
src/lib/erc20.ts

feat: bump llamafolio-tokens

---

scripts/update-missing-tokens.ts

Fix: update missing tokens script

---

src/db/history.ts
src/handlers/getHistory.ts

Group adapters contracts into an array to prevent duplicates

fix: history duplicates

---

.vscode/launch.json
src/adapters/azuro/arbitrum/index.ts
src/adapters/azuro/common/balance.ts
src/adapters/azuro/gnosis/index.ts
src/adapters/azuro/index.ts
src/adapters/azuro/polygon/index.ts
src/adapters/index.ts

POLYGON
`pnpm run adapter azuro polygon 0xf9f061d9a5f04e223ed3c560e03a8ab0a70cc1c4`
ARBITRUM
`pnpm run adapter azuro arbitrum 0x11d67fa925877813b744abc0917900c2b1d6eb81`
GNOSIS
`pnpm run adapter azuro gnosis 0x458cd345b4c05e8df39d0a07220feb4ec19f5e6f`

feat: Adapter, Azuro

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/trufin-protocol/ethereum/balance.ts
src/adapters/trufin-protocol/ethereum/index.ts
src/adapters/trufin-protocol/index.ts

`pnpm run adapter trufin-protocol ethereum 0x3d66dd9c9cf2ee749f1fa743dad336b84254221f`

feat: Adapter, trufin-protocol

---

package.json
pnpm-lock.yaml
src/lib/chains.ts
src/lib/providers/chains.ts

bump: tokens

---

src/adapters/azuro/index.ts
src/adapters/coinbase-wrapped-staked-eth/arbitrum/index.ts
src/adapters/coinbase-wrapped-staked-eth/index.ts
src/adapters/coinbase-wrapped-staked-eth/optimism/index.ts
src/adapters/coinbase-wrapped-staked-eth/polygon/index.ts

- Arbitrum support
- Base support
- Optimism support
- Polygon support

feat: coinbase wrapped staked eth multi chain

---

package.json
pnpm-lock.yaml

bump: llamafolio-tokens 0.1.90

---

src/adapters/lybra-v2/arbitrum/farm.ts
src/adapters/lybra-v2/arbitrum/index.ts
src/adapters/lybra-v2/index.ts

`pnpm run adapter-balances lybra-v2 ethereum 0x66b870ddf78c975af5cd8edc6de25eca81791de1`

feat: update lybra-v2, add ARB chain

---

.vscode/launch.json
src/lib/chains.ts

add ZkSyncEra chain

---

src/adapters/granary-finance/arbitrum/index.ts
src/adapters/granary-finance/base/index.ts
src/adapters/granary-finance/bsc/index.ts
src/adapters/granary-finance/index.ts

ARBITRUM
`pnpm run adapter granary-finance arbitrum 0xc19ed1fa9fa3968fe12e97aa4d511ab6bce1320f`
BSC
`pnpm run adapter granary-finance bsc 0x3d3dc4b0445f1063644e9d0b2ba1c66f7958f248`
BASE
`pnpm run adapter granary-finance base 0xbdb399dd6f66609303d906d90765e432c04f77a4`
OPTIMISM
`pnpm run adapter granary-finance optimism 0x8929c3f0cca2aa8ad28389381a2ba102e8ea0a7f`

feat: Update Granary-Finance alt chains

---

src/adapters/gamma/avalanche/index.ts
src/adapters/gamma/base/index.ts
src/adapters/gamma/index.ts
src/adapters/gamma/moonbeam/index.ts
src/adapters/gamma/optimism/index.ts

feat: update Gamma alt chains

---

serverless.yml
src/db/contracts.ts
src/handlers/getContract.ts

Simpler single-chain version as the multi-chain one is no longer used

feat: get contract by chain

---

scripts/build-adapters.ts
scripts/create-adapter.ts
src/lib/fmt.ts

fix: create-adapter script handle chain names with spaces

---

serverless.yml

feat: increase getContract timeout

---

src/adapters/uniswap-v2/ethereum/index.ts
src/lib/erc20.ts
src/lib/token.ts

fix: get tokens native

---

src/adapters/convex-finance/ethereum/balance.ts
src/adapters/convex-finance/ethereum/index.ts
src/adapters/curve-dex/common/pool.ts

rm duplicates with functionnal testing tool

Fix duplicates and test tools

---

package.json
pnpm-lock.yaml
src/lib/providers/chains.ts

bump: llamafolio-tokens 0.1.93

---

src/adapters/stargate/common/contract.ts

> we were not able to revalidate the contracts
Fixed now

small fix Stargate

---

src/lib/chains.ts

feat: LlamaNodes Optimism support

---

src/handlers/getBalances.ts
src/handlers/updateBalances.ts

fix: balances use token when possible

---

src/handlers/getProtocols.ts

feat: get protocols swr header

---

serverless.yml
src/db/balances.ts
src/handlers/getHistory.ts
src/handlers/getLatestSnapshot.ts

fix: balances snapshots

---

src/handlers/getBalancesTokens.ts

fix: get wallet interactions

---

src/adapters/retro/polygon/index.ts

feat: Update, retro, add locker

---

src/db/contracts.ts
src/handlers/getToken.ts

fix: optimize get token query

---

src/db/history.ts

fix: history query include timestamp

---

src/db/contracts.ts

optimize query to prevent merging parts at select time

fix: get wallet interactions query

---

src/db/history.ts
src/handlers/getHistory.ts
src/lib/erc20.ts

feat: history endpoint token details

---

src/db/contracts.ts

fix: get contract interactions query

---

src/adapters/beefy/common/boost.ts

> add exchangeRate on boosted pools

fix: adapter, beefy

---

src/db/balances.ts
src/handlers/updateBalances.ts

fix: health factor

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/liquid-collective/ethereum/balance.ts
src/adapters/liquid-collective/ethereum/index.ts
src/adapters/liquid-collective/index.ts

`pnpm run adapter-balances liquid-collective ethereum 0xa6941e15b15ff30f2b2d42ae922134a82f6b7189`

feat: Adpater, liquid-collective

---

src/handlers/getHistory.ts
src/lib/price.ts

fix: mulPrice fallback value

---

src/adapters/prisma-finance/ethereum/balance.ts
src/adapters/prisma-finance/ethereum/index.ts
src/adapters/prisma-finance/ethereum/pool.ts

`pnpm run adapter-balances prisma-finance ethereum 0xbdfa4f4492dd7b7cf211209c4791af8d52bf5c50`

add new pools, fix farm logic with handling error

---

src/lib/balance.ts

fix: update balances rewards

---

package.json
pnpm-lock.yaml

bump: llamafolio-tokens 0.1.96

---

src/adapters/synthetix/common/balance.ts
src/adapters/synthetix/ethereum/index.ts
src/adapters/synthetix/optimism/index.ts

fix: SNX interactions

---

src/db/contracts.ts
src/handlers/updateBalances.ts

fix: always run wallet adapter

---

src/db/balances.ts

fix: balances yields underlyings

---

src/adapters/convex-finance/ethereum/index.ts
src/adapters/convex-finance/ethereum/stake.ts

fix: Convex mising stkCrvCvx

---

src/adapters/hop-protocol/index.ts

> Comment on Gnosis as long as we don't index the chain

feat: Adapter, hop-protocol

---

environment.ts
src/db/adapters.ts
src/db/contracts.ts
src/db/protocols.ts

feat: dev tables

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/preon-finance/arbitrum/index.ts
src/adapters/preon-finance/common/balance.ts
src/adapters/preon-finance/index.ts
src/adapters/preon-finance/polygon/index.ts

`pnpm run adapter-balances preon-finance arbitrum 0x1d214979316b66b5760b142b63b63506506189b4`
`pnpm run adapter-balances preon-finance polygon 0x9c20b6eb1452e6ad77d67a8b5d86fddc384e93f3`

feat: Adapter, preon-finance

---

.vscode/launch.json
src/adapters/ambient/ethereum/balance.ts
src/adapters/ambient/ethereum/index.ts
src/adapters/ambient/ethereum/pool.ts
src/adapters/ambient/index.ts
src/adapters/index.ts

`pnpm run adapter-balances ambient ethereum 0x6737df00ef1e6160d9e53677eedbbcc7b95c54e1`
`pnpm run adapter-balances ambient ethereum 0x7f065ce53c4a97165ab0c83c4d796f79a8f93fc9`
`pnpm run adapter-balances ambient ethereum 0x634eeef5d8314e0f0056c11f4d1b1837c32ba10f`

feat: Adapter, Ambient

---

scripts/utils/balances.ts
src/adapters/prisma-finance/ethereum/balance.ts
src/db/balances.ts
src/handlers/updateBalances.ts
src/lib/adapter.ts
src/lib/balance.ts
src/lib/math.ts

Resolve health factor using MCR and collateral + debt balances

feat: health factor using MCR

---

src/adapters/illuvium/ethereum/balance.ts
src/adapters/illuvium/ethereum/index.ts

`pnpm run adapter-balances illuvium ethereum 0xa804fb037f275572b9e6ae8cba1dc9f0789745b6`
`pnpm run adapter-balances illuvium ethereum 0x330cd7f45f06bc08c1619d286ff0bd82df080887`

feat: Adapter, Illuvium, [missing pools & rewards]

---

src/adapters/verse/ethereum/balance.ts
src/adapters/verse/ethereum/contract.ts
src/adapters/verse/ethereum/index.ts

`pnpm run adapter-balances verse ethereum 0x717d52e84eF30875De52834603c112675CeDB7CA`

feat: Adapter, Verse, add missing pool, fix interactions

---

scripts/revalidate-contracts-rec.ts
scripts/revalidate-contracts.ts
scripts/update-governance-proposals.ts
serverless.yml
src/db/adapters.ts
src/db/balances.ts
src/db/calendar.ts
src/db/governance.ts
src/handlers/getCalendar.ts
src/handlers/revalidateAdapters.ts
src/handlers/updateGovernanceProposals.ts
src/lib/calendar.ts
src/lib/fmt.ts
src/lib/governance.ts
src/lib/lambda.ts
src/lib/protocols.ts

- add protocol parent in DB 
- add calendar endpoint
- add governance proposals

feat: calendar api

---

src/db/calendar.ts

fix: calendar api governance proposals rm duplicates

---

src/db/protocols.ts
src/lib/protocols.ts

Attach parent protocol slug to the response (if exists)

feat: protocols api parent

---

scripts/update-governance-proposals.ts
src/db/calendar.ts
src/db/governance.ts
src/handlers/updateGovernanceProposals.ts
src/lib/governance.ts

feat: governance add sources compound and tally

---

src/db/balances.ts
src/handlers/getBalances.ts
src/handlers/updateBalances.ts
src/lib/yields/index.ts

This prevents having multiple groups with same chain and same protocol (and potentially forgetting one) and help adding metadata at the protocol level (now that balances are not "spread" in the response anymore)

feat: balances api group protocol balances together

---

package.json
pnpm-lock.yaml

bump: viem 1.14.0

---

src/handlers/getCalendar.ts
src/lib/calendar.ts
src/lib/ens.ts

feat: calendar ENS registrations

---

src/db/balances.ts
src/handlers/updateBalances.ts
src/lib/balance.ts

fix: collat factor HF

---

src/adapters/fraxlend/ethereum/lend.ts
src/adapters/fraxlend/ethereum/registry.ts

> move logic to retrieve CF in getBalances instead of getContracts

HF in getBalances instead of getContracts

---

src/adapters/conic-finance/ethereum/balance.ts
src/adapters/conic-finance/ethereum/contract.ts
src/adapters/conic-finance/ethereum/index.ts

`pnpm run adapter conic-finance ethereum 0x20cc6cf5b44ff68b6ffbb95f8b21e876d4611c20`

fix: Adapter, CNC

---

src/adapters/aave-v3/common/lending.ts
src/lib/aave/v2/lending.ts

`stable` flag is used to know if the position is volatile or not

fix: aave stable flag

---

scripts/utils/balances.ts
src/db/balances.ts

> Fix stable_distribution display

Fix: stable distribution

---

src/adapters/pearlfi/polygon/index.ts

feat: Adapter, PearlFi

---

src/adapters/velodrome-v2/optimism/pair.ts

> Add a small fix to prevent issues when trying to revalidate if bribes isnt provide to the pool

Fix: Adapter, Velo & forks (bribes)

---

src/adapters/agility-lsd/ethereum/stake.ts
src/adapters/annex/bsc/balance.ts
src/lib/call.ts
src/lib/multicall.ts
src/lib/uniswap/v2/pair.ts

feat: uni balance resolver continue even if no underlyings defined

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/seamless-protocol/base/index.ts
src/adapters/seamless-protocol/index.ts

feat: seamless-protocol lending

---

src/adapters/curve-dex/common/balance.ts
src/adapters/curve-dex/common/gauge.ts
src/adapters/curve-dex/common/pool.ts
src/adapters/curve-dex/common/registries.ts
src/adapters/curve-dex/ethereum/index.ts
src/adapters/curve-dex/ethereum/pools.ts
src/db/contracts.ts

use standard `token` field instead of `lpToken`

feat: adapters contracts token field

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/mean-finance/arbitrum/index.ts
src/adapters/mean-finance/bsc/index.ts
src/adapters/mean-finance/common/balance.ts
src/adapters/mean-finance/ethereum/index.ts
src/adapters/mean-finance/index.ts
src/adapters/mean-finance/optimism/index.ts
src/adapters/mean-finance/polygon/index.ts

`pnpm run adapter-balances mean-finance arbitrum 0x99e4d43482db810fc5095f04029d0ee62b3fecbd`
`pnpm run adapter-balances mean-finance polygon 0x5e2044c2b5eb57b17ce382c1856a1de3166c460a`
`pnpm run adapter-balances mean-finance optimism 0x280f9b5e49c08972d1d618c91d02a160873ae369`

Feat: Adapter, Mean finance

---

scripts/revalidate-contracts-rec.ts
scripts/revalidate-contracts.ts
scripts/run-adapter.ts
src/adapters/0vix/polygon/index.ts
src/adapters/wallet/index.ts
src/db/contracts.ts
src/handlers/revalidateAdapters.ts
src/lib/adapter.ts
src/lib/compound/v2/lending.ts
src/lib/token.ts

The execution context always contains the chain so it's duplicate info to specify the chain on each Contract. 
Overall it's easier to reason in the context of a single chain

refactor: optional chain prop in Contract

---

scripts/utils/balances.ts
src/adapters/0vix/polygon/index.ts
src/adapters/alchemix/ethereum/index.ts
src/adapters/alchemix/fantom/index.ts
src/adapters/curve-dex/ethereum/index.ts
src/adapters/wallet/index.ts
src/db/contracts.ts
src/lib/adapter.ts
src/lib/compound/v2/lending.ts
src/lib/token.ts

feat: get underlyings from db

---

src/adapters/convex-finance/common/pool.ts
src/adapters/curve-dex/common/balance.ts
src/adapters/curve-dex/common/gauge.ts
src/adapters/curve-dex/common/pool.ts
src/adapters/curve-dex/ethereum/index.ts
src/adapters/curve-dex/ethereum/pools.ts

Revert last changes, replace token -> lpToken as before + revalidate

small fix on curve-dex, revert last changes

---

.vscode/launch.json
src/adapters/goodentry/arbitrum/balance.ts
src/adapters/goodentry/arbitrum/index.ts
src/adapters/goodentry/arbitrum/pool.ts
src/adapters/goodentry/index.ts
src/adapters/index.ts
src/adapters/stargate/arbitrum/index.ts

`pnpm run adapter-balances goodentry arbitrum 0x14975679e5f87c25fa2c54958e735a79b5b93043`

feat: Adapter, GoodEntry

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/umami-finance/arbitrum/balance.ts
src/adapters/umami-finance/arbitrum/index.ts
src/adapters/umami-finance/arbitrum/pool.ts
src/adapters/umami-finance/index.ts

`pnpm run adapter-balances umami-finance arbitrum 0xb137d135dc8482b633265c21191f50a4ba26145d`
`pnpm run adapter-balances umami-finance arbitrum 0x1922c36f3bc762ca300b4a46bb2102f84b1684ab`
`pnpm run adapter-balances umami-finance arbitrum 0xdca4e88c00a8800ebcebad63abdbaaaa755557f9`

feat: Adapter, Umami-finance

---

src/db/contracts.ts

See: https://github.com/llamafolio/llamafolio-api/issues/970

fix: missing token field contract interaction

---

src/adapters/parallel-protocol/common/stake.ts
src/adapters/parallel-protocol/ethereum/index.ts
src/adapters/parallel-protocol/fantom/index.ts
src/adapters/parallel-protocol/polygon/index.ts

> fix interactions with rewards

fix interactions

---

src/adapters/morpho-aavev3/ethereum/balance.ts

> Add simple liquidity provider from user logic
`pnpm run adapter-balances morpho-aavev3 ethereum 0x741aa7cfb2c7bf2a1e7d4da2e3df6a56ca4131f3`

Feat:Adapter,MorphoAavev3 [Logic]

---

src/lib/chains.ts

feat: Base LlamaNodes

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/notional/common/balance.ts
src/adapters/notional/common/pool.ts
src/adapters/notional/ethereum/index.ts
src/adapters/notional/index.ts

`pnpm run adapter-balances notional ethereum 0x741aa7cfb2c7bf2a1e7d4da2e3df6a56ca4131f3`
`pnpm run adapter-balances notional ethereum 0x741aa7cfb2c7bf2a1e7d4da2e3df6a56ca4131f3`

[WIP] - Feat: Adapter, Notional

---

src/lib/multicall.ts

add option to `allowFailure: false` for simpler cases when we know reading these functions won't fail

feat: multicall allowFailure option

---

src/adapters/metronome/ethereum/balance.ts

fix: Metronome, pricePerShare

---

src/adapters/velodrome-v2/optimism/balance.ts

> add an error handler to avoid blocking the function if a balance is zero

small fix, prevent null balance

---

src/adapters/velodrome-v2/optimism/locker.ts

Fix: Aerodrome locker, handler if null token

---

src/adapters/crvusd/ethereum/balance.ts
src/adapters/crvusd/ethereum/contract.ts
src/adapters/crvusd/ethereum/index.ts

refactor: crvusd naming

---

src/adapters/kwenta/index.ts
src/adapters/kwenta/optimism/balance.ts
src/adapters/kwenta/optimism/index.ts
src/adapters/kwenta/optimism/vest.ts

> Add missing vesting & staking contracts
`pnpm run adapter-balances kwenta optimism 0x1aaefe8c14e6670579396cd5eed4d478f27a9b9b`
`pnpm run adapter-balances kwenta optimism 0x12478d1a60a910c9cbffb90648766a2bdd5918f5`

Update, Adapter, Kwenta

---

src/adapters/metronome/common/balance.ts
src/adapters/metronome/common/contract.ts
src/adapters/metronome/index.ts
src/adapters/metronome/optimism/index.ts

> Add Optimism chain + rewardDistributor
> /!\ msTokens prices are not known on Defillama API
`pnpm run adapter-balances metronome optimism 0x37a6156e4a6e8b60b2415af040546cf5e91699bd`
`pnpm run adapter-balances metronome optimism 0x73831e7c600f48cebbbff957b466be8e5c087f34`

Update: Adapter, Metronome

---

src/lib/chains.ts

Fallback to Free LlamaNodes RPC if no Premium API key specified (instead of not using it at all)

feat: use LlamaNodes free RPC if no Premium API key provided

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/tender-finance/arbitrum/index.ts
src/adapters/tender-finance/arbitrum/stake.ts
src/adapters/tender-finance/index.ts

> /!\ esTND price isnt know by Defillama API
`pnpm run adapter-balances tender-finance arbitrum 0x1f6213beeb06dc5e401f647fde3282979cde00bd`
`pnpm run adapter-balances tender-finance arbitrum 0x703dfcd90b7003549dd89e97d541137ecb03c4d2`
`pnpm run adapter-balances tender-finance arbitrum 0xe24d5da3d7a49ba52f231bb5386f1fbc8e79c122`

feat: Adapter, Tender-Finance (lend cForks + stake)

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/mesher/ethereum/index.ts
src/adapters/mesher/index.ts

`pnpm run adapter-balances mesher ethereum 0xac89a53c033d5146da003ee21ac8fadb5ac34db3`

Feat: Adapter, Mesher

---

.vscode/launch.json
src/adapters/cozy-finance/ethereum/index.ts
src/adapters/cozy-finance/index.ts
src/adapters/index.ts

`pnpm run adapter-balances cozy-finance ethereum 0x7877ee0c7355ad7755d794f87da5902109e76575`

feat: Adapter, Cozy-finance

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/usdfi-lending/bsc/index.ts
src/adapters/usdfi-lending/index.ts

`pnpm run adapter-balances usdfi-lending bsc 0x5ea5522fa9a086e58185e507b3524943bbe96415`

feat: Adapter, USDFI

---

src/adapters/prisma-finance/ethereum/balance.ts
src/adapters/prisma-finance/ethereum/index.ts

> Add rewards on Prisma vaults, stab pool, farming pools
pnpm run adapter-balances prisma-finance ethereum 0x9026a229b535ecf0162dfe48fdeb3c75f7b2a7ae`
`

Prisma_addRewards

---

src/handlers/getBalancesV1.ts
src/handlers/response.ts

feat: balances v1 cache-control

---

serverless.yml
src/handlers/getBalances.ts

update v1 changes to v0 (downtime reason)

feat: balances api v0

---

src/db/balances.ts

Aggregate "wallet" balances for bundles. This scenario is very simple and there's no ambiguity (compared to protocols)

feat: balances api aggregate wallet

---

src/adapters/magpie/ethereum/index.ts
src/adapters/magpie/optimism/index.ts

Fix: Magpie import

---

src/adapters/notional/common/balance.ts

Notional fix lend graphQl was not dynamic

---

package.json
pnpm-lock.yaml
src/lib/providers/chains.ts

This change concerns a small chore/refactor.
Replace the manual overwrite of Gnosis chain that was done in order to add the multicall contract; now that the changes made have been added to the upstream and released.
Improve codebase readability and maintainability.
> Source: https://github.com/wagmi-dev/viem/blob/main/src/chains/definitions/gnosis.ts#L32

chore: Gnosis chain config

---

src/adapters/abracadabra/common/masterchef.ts
src/adapters/across/ethereum/v2/balance.ts
src/adapters/alien-base/base/balance.ts
src/adapters/alien-base/base/index.ts
src/adapters/annex/bsc/balance.ts
src/adapters/annex/bsc/contract.ts
src/adapters/annex/bsc/index.ts
src/adapters/apeswap-amm/bsc/index.ts
src/adapters/apeswap-amm/bsc/reward.ts
src/adapters/apeswap-amm/polygon/contract.ts
src/adapters/apeswap-amm/polygon/index.ts
src/adapters/arbitrum-exchange/arbitrum/balance.ts
src/adapters/arbitrum-exchange/arbitrum/index.ts
src/adapters/baseswap/base/balance.ts
src/adapters/baseswap/base/index.ts
src/adapters/baseswap/base/reward.ts
src/adapters/benddao/ethereum/nft.ts
src/adapters/benqi-staked-avax/avalanche/stake.ts
src/adapters/magpie/common/magpie.ts
src/adapters/magpie/common/penpie.ts
src/adapters/magpie/common/radpie.ts
src/adapters/mdex/bsc/index.ts
src/lib/chains.ts
src/lib/masterchef/masterChefBalance.ts
src/lib/masterchef/masterChefContract.ts
src/lib/masterchef/newMasterchef.ts

Refacto using New MasterChef lib

---

src/adapters/convex-finance/ethereum/index.ts
src/adapters/convex-finance/ethereum/prisma.ts

feat: convex prisma

---

src/adapters/aave-v3/gnosis/index.ts
src/adapters/aave-v3/index.ts

`pnpm run adapter aave-v3 gnosis 0x458cd345b4c05e8df39d0a07220feb4ec19f5e6f`
`pnpm run adapter aave-v3 gnosis 0x5e46f0d1b3e1cf21d584fb557f98eb3ea4a19059`

Update: Aave, Gnosis chain

---

src/handlers/updateBalances.ts

fix: export update-balances

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/zerolend/index.ts
src/adapters/zerolend/zksync-era/index.ts

feat: zerolend lend

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/realt/gnosis/contract.ts
src/adapters/realt/gnosis/index.ts
src/adapters/realt/index.ts

`pnpm run adapter realt gnosis 0x3a662f787168e8d856e801c75449876f4da9208a`

feat: Adapter, RealT

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/sdai/gnosis/balance.ts
src/adapters/sdai/gnosis/index.ts
src/adapters/sdai/index.ts

`pnpm run adapter sdai gnosis 0x9f0a988edc96dac834c158ebfe667da932bd87c6`
`pnpm run adapter sdai gnosis 0x79c4213a328e3b4f1d87b4953c14759399db25e2`

Feat: Adapter, sDAI (mu.exchange)

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/sdai/gnosis/balance.ts
src/adapters/sdai/gnosis/index.ts
src/adapters/sdai/index.ts

`pnpm run adapter sdai gnosis 0x9412fecb99d0b8e95631596bff2a927e1f9fbf70`

Feat: Adapter, sDAI

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/levinswap/gnosis/index.ts
src/adapters/levinswap/index.ts

`pnpm run adapter levinswap gnosis 0x0f2b0e9db46c6b538e9276d2cf0c6ce8d515eca1`
`pnpm run adapter levinswap gnosis 0x5fc96c182bb7e0413c08e8e03e9d7efc6cf0b099`

Feat: Adapter, Levinswap

---

.vscode/launch.json
src/adapters/hopr/gnosis/balance.ts
src/adapters/hopr/gnosis/contract.ts
src/adapters/hopr/gnosis/index.ts
src/adapters/hopr/index.ts
src/adapters/index.ts

`pnpm run adpater hopr gnosis 0x768f2a7ccdfde9ebdfd5cea8b635dd590cb3a3f1`
`pnpm run adpater hopr gnosis 0x6083aca8248cf7f399033df396809bf72d0b581c`

Feat: Adapter, Hopr

---

src/adapters/convex-finance/ethereum/fx.ts
src/adapters/convex-finance/ethereum/index.ts

feat: convex f(x)

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/swapr/arbitrum/index.ts
src/adapters/swapr/common/balance.ts
src/adapters/swapr/common/pool.ts
src/adapters/swapr/ethereum/index.ts
src/adapters/swapr/gnosis/index.ts
src/adapters/swapr/index.ts

GNOSIS
`pnpm run adapter swapr gnosis 0xf71d161fdc3895f21612d79f15aa819b7a3d296a`
`pnpm run adapter swapr gnosis 0x58425672c7c17336b91092ac13e2f37bcc4185b7`
ARBITRUM
`pnpm run adapter swapr arbitrum 0xa074b949e9cfc3edce8f6ca4e2ad4a9ea9e08324`
`pnpm run adapter swapr arbitrum 0x22f340c2604dc1cdbe26cac5838ea9ebc8862a46`

Feat: Adapter, Swapr

---

.vscode/launch.json
src/adapters/giveth/gnosis/balance.ts
src/adapters/giveth/gnosis/index.ts
src/adapters/giveth/gnosis/pool.ts
src/adapters/giveth/gnosis/reward.ts
src/adapters/giveth/index.ts
src/adapters/index.ts

`pnpm run adapter giveth gnosis 0xa32aecda752cf4ef89956e83d60c04835d4fa867`
`pnpm run adapter giveth gnosis 0x981e7512e87d2f7228d3f03b65950eb6a1b21bac`

Feat: Adapter, Giveth

---

src/adapters/convex-finance/ethereum/frax.ts
src/adapters/convex-finance/ethereum/fx.ts
src/adapters/convex-finance/ethereum/index.ts
src/adapters/convex-finance/ethereum/prisma.ts

- add stkCvxFxs
- add stkCvxFpis
- refactor generic logic for f(x) and prisma

feat: convex frax staking

---

scripts/insert-llamafolio-tokens.ts
src/db/tokens.ts
src/handlers/getToken.ts
src/lib/coingecko.ts
src/lib/fmt.ts

Simplify token handler to retrieve only token data

fix: token handler

---

scripts/find-user.ts
src/labels/ens/index.ts

Fix `find-user` script, it's not used at the moment but could be helpful to add custom tags on top of the ones from DefiLlama
Example: `vitalik.eth`
```bash
npx tsx scripts/find-user.ts 0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045
```

fix: label get ENS name

---

scripts/find-user.ts
src/labels/llamafolio/index.ts
src/labels/opensea/index.ts

Improve typings and documentation around `find-user` script; and handle HTTP errors
Example: `vitalik.eth`
```
npx tsx scripts/find-user.ts 0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045
```

fix: Find User script

---

.vscode/launch.json
src/adapters/compound-v3/common/asset.ts
src/adapters/index.ts
src/adapters/solv-protocol/arbitrum/index.ts
src/adapters/solv-protocol/bsc/index.ts
src/adapters/solv-protocol/common/balance.ts
src/adapters/solv-protocol/common/pool.ts
src/adapters/solv-protocol/common/vesting.ts
src/adapters/solv-protocol/ethereum/index.ts
src/adapters/solv-protocol/index.ts
src/adapters/solv-protocol/polygon/index.ts

`pnpm run adapter-balances solv-protocol ethereum 0x5cedce4b14355aa35a1a65f018514b777a3d0cbb`

Feat: Adapter, Solv-Protocol

---

.vscode/launch.json
src/adapters/get-protocol/common/balance.ts
src/adapters/get-protocol/ethereum/index.ts
src/adapters/get-protocol/index.ts
src/adapters/get-protocol/polygon/index.ts
src/adapters/index.ts

`pnpm run adapter get-protocol ethereum 0xa6691bbde58538747d38f03dd3363bf1d917cd4e`
`pnpm run adapter get-protocol polygon 0xc58b20c01c1f24e72ee2c36a773ef48e774ea595`

feat: Adapter, Get-protocol

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/kine-finance/bsc/index.ts
src/adapters/kine-finance/common/farm.ts
src/adapters/kine-finance/common/lp.ts
src/adapters/kine-finance/ethereum/index.ts
src/adapters/kine-finance/index.ts
src/adapters/kine-finance/polygon/index.ts

`pnpm run adapter kine-finance ethereum 0x6ef2376fa6e12dabb3a3ed0fb44e4ff29847af68`
`pnpm run adapter kine-finance ethereum 0x2b6f908bf9082ad39adb27c04e88adfec8f58110`

Feat, Adapter, Kine-finance

---

.vscode/launch.json
src/adapters/bifrost-liquid-staking/ethereum/balance.ts
src/adapters/bifrost-liquid-staking/ethereum/index.ts
src/adapters/bifrost-liquid-staking/index.ts
src/adapters/index.ts

`pnpm run adapter bifrost-liquid-staking ethereum 0x7822159ee394d14745cde63a706f965fb73c7ac8`
`pnpm run adapter bifrost-liquid-staking ethereum 0x674bdf20a0f284d710bc40872100128e2d66bd3f`

Feat: Adapter, Bifrost (vETH LST)

---

.vscode/launch.json
src/adapters/fx-protocol/ethereum/balance.ts
src/adapters/fx-protocol/ethereum/index.ts
src/adapters/fx-protocol/index.ts
src/adapters/index.ts

`pnpm run adapter fx-protocol ethereum 0x488b99c4a94bb0027791e8e0eeb421187ec9a487`
`pnpm run adapter fx-protocol ethereum 0xd11a4ee017ca0beca8fa45ff2abfe9c6267b7881`

feat: Adapter, fx-protocol

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/mountain-protocol/ethereum/balance.ts
src/adapters/mountain-protocol/ethereum/index.ts
src/adapters/mountain-protocol/index.ts

`pnpm run adapter mountain-protocol ethereum 0xba12222222228d8ba445958a75a0704d566bf2c8`

Feat: Adapter, Mountain-protocol

---

serverless.yml
src/db/balances.ts
src/handlers/getTokenHolders.ts
src/handlers/updateBalances.ts
src/lib/chains.ts

feat: token holders

---

src/handlers/getToken.ts

feat: getToken totalSupply

---

src/handlers/getInfoAddress.ts
src/lib/fmt.ts

feat: update getInfoAddress

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/thales/arbitrum/index.ts
src/adapters/thales/base/index.ts
src/adapters/thales/common/market.ts
src/adapters/thales/common/stake.ts
src/adapters/thales/index.ts
src/adapters/thales/optimism/index.ts

`pnpm run adapter-balances thales optimism 0x1777c6d588fd931751762836811529c0073d6376`
`pnpm run adapter-balances thales arbitrum 0x1777c6d588fd931751762836811529c0073d6376`

Feat: Adapter, Thales

---

src/adapters/thales/base/index.ts

Small fix, there was an issue on base, contract had wrong chain props

Fix, veThales arb -> base

---

.vscode/launch.json
src/adapters/amphor/ethereum/balance.ts
src/adapters/amphor/ethereum/index.ts
src/adapters/amphor/index.ts
src/adapters/index.ts

`pnpm run adapter-balances amphor ethereum 0xc5c75caf067ae899a7ec10b86b5ab38c13879388`
`pnpm run adapter-balances amphor ethereum 0x7822159ee394d14745cde63a706f965fb73c7ac8`

Feat, Adapter, Amphor

---

.vscode/launch.json
src/adapters/arc-swap/ethereum/index.ts
src/adapters/arc-swap/ethereum/reward.ts
src/adapters/arc-swap/index.ts
src/adapters/index.ts

`pnpm run adapter arc-swap ethereum 0xab9c793344d16504a5073368fd030e73cc621cb0`
`pnpm run adapter arc-swap ethereum 0xd79ee3be5e0154cd7540a55cc4f7e44d78a38b6a`

Feat: Adapter, Arc-swap (masterChef)

---

.vscode/launch.json
src/adapters/centrifuge/ethereum/balance.ts
src/adapters/centrifuge/ethereum/index.ts
src/adapters/centrifuge/ethereum/pool.ts
src/adapters/centrifuge/index.ts
src/adapters/index.ts

`pnpm run adapter-balances centrifuge ethereum 0x1bd5d6e5d95393a3175c56683b2cb9ddb3188fc1`

Feat: Adapter, Centrifuge

---

serverless.yml

feat: serverless config timeout

---

.vscode/launch.json
src/adapters/equilibria/arbitrum/index.ts
src/adapters/equilibria/bsc/index.ts
src/adapters/equilibria/common/balance.ts
src/adapters/equilibria/common/lock.ts
src/adapters/equilibria/common/pool.ts
src/adapters/equilibria/ethereum/index.ts
src/adapters/equilibria/index.ts
src/adapters/equilibria/optimism/index.ts
src/adapters/index.ts
src/lib/masterchef/masterChefContract.ts

`pnpm run adapter-balances equilibria ethereum 0x9026a229b535ecf0162dfe48fdeb3c75f7b2a7ae`
`pnpm run adapter-balances equilibria ethereum 0xc5c75caf067ae899a7ec10b86b5ab38c13879388`

Equilibria

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/kinza-finance/bsc/index.ts
src/adapters/kinza-finance/index.ts
src/adapters/kinza-finance/opbnb/index.ts

`pnpm run adapter kinza-finance bsc 0xfdc2e337c1c8ffc1e4fee526441ef6c7a447bd81`
`pnpm run adapter kinza-finance bsc 0x438bbff80252c9c959797d0180a5c868e1a86c91`
`pnpm run adapter kinza-finance opbnb 0x934df3679a8678bee94b786014e19dd74a7f542c`

feat: adapter, Kinza-finance

---

src/adapters/radiant-v2/ethereum/index.ts
src/adapters/radiant-v2/ethereum/multifee.ts
src/adapters/radiant-v2/index.ts

`pnpm run adapter radiant-v2 ethereum 0xaf0fdd39e5d92499b0ed9f68693da99c0ec1e92e`

Update, RadiantCapital, Ethereum

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/perpetual-protocol/common/balance.ts
src/adapters/perpetual-protocol/ethereum/index.ts
src/adapters/perpetual-protocol/index.ts
src/adapters/perpetual-protocol/optimism/index.ts

` pnpm run adapter perpetual-protocol optimism 0x8c2cb288ab3d18b92826d980313ddad33cfbc920`

Feat:Adapter, Perpetual-protocol

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/spice-finance/ethereum/balance.ts
src/adapters/spice-finance/ethereum/index.ts
src/adapters/spice-finance/index.ts

`pnpm run adapter spice-finance ethereum 0x2b605c2a76ee3f08a48b4b4a9d7d4dad3ed46bf3`
`pnpm run adapter spice-finance ethereum 0x5d28a7af78635d4f4c0bf5c404241a941a7ebd0a`

Feat:Adapter,Spice-Finance

---

src/adapters/looksrare/ethereum/balances.ts
src/adapters/looksrare/ethereum/index.ts

Introducing support for the new staking contracts of LooksRare; for both classic ([stake LOOKS, earn WETH](https://etherscan.io/address/0x0000000000017b2a2a6a336079Abc67f6f48aB9A#readContract)), and compounder ([stake LOOKS, earn LOOKS](https://etherscan.io/address/0x000000000077ee1fcfe351df1ff22736e995806b#readContract)).
> https://docs.looksrare.org/blog/the-looks-rewards-migration
Staking:
Compounder:

feat(looksrare): Staking contracts (v2)

---

scripts/utils/balances.ts
src/lib/fmt.ts

It's better to show full values (not truncated) to debug protocol adapters

feat: run-adapter scripts show full values

---

src/db/contracts.ts
src/handlers/getContract.ts

use built-in contracts table to allow us adding metadata later on (ABI, name, verified)

feat: refactor getContract handler

---

scripts/utils/balances.ts
src/db/balances.ts
src/lib/balance.ts
src/lib/price.ts

fix: https://github.com/llamafolio/llamafolio-api/issues/1013
Keep wallet balances even if we're missing the token price (better to see the amount than nothing)

feat: keep unpriced balances

---

src/adapters/ondo-finance/index.ts
src/adapters/ondo-finance/polygon/index.ts

`pnpm run adapter ondo-finance polygon 0x27ee3d1f71f41dead9661ea092f236b4bd14f380`

Update,Ondo-Finance, Polygon

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/soswap/base/index.ts
src/adapters/soswap/index.ts

`pnpm run adapter soswap base 0x4f0d938a81343a5fb10d6bb20bf5996e2e557586`
`pnpm run adapter soswap base 0x83c1e5e2f71d0bc06db66dc0854b447c7d369f70`

Feat:Adapter,Soswap,Base

---

scripts/update-tokens.ts
src/db/tokens.ts
src/lib/adapter.ts
src/lib/promise.ts

fix: update tokens script

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/kokonut-swap/base/index.ts
src/adapters/kokonut-swap/base/pool.ts
src/adapters/kokonut-swap/index.ts

`pnpm run adapter kokonut-swap base 0x5593b57d06458f62b1a4f31a997945a3b51fc2fd`

feat:Adapter,KokonutSwap,Base

---

src/adapters/fraxlend/ethereum/index.ts
src/adapters/fraxlend/ethereum/lend.ts

#1089 
Split BalancesGroups, fix decimals,

Frax, split balances, fix decimals

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/rubicon/index.ts
src/adapters/rubicon/optimism/balance.ts
src/adapters/rubicon/optimism/index.ts
src/adapters/rubicon/optimism/pool.ts

`pnpm run adapter rubicon optimism 0x3204ac6f848e05557c6c7876e09059882e07962f`

Feat:Adapter,Rubicon,Optimism

---

.vscode/launch.json
src/adapters/clearpool/common/balance.ts
src/adapters/clearpool/common/pool.ts
src/adapters/clearpool/ethereum/index.ts
src/adapters/clearpool/index.ts
src/adapters/clearpool/optimism/index.ts
src/adapters/clearpool/polygon/index.ts
src/adapters/index.ts

`pnpm run adapter clearpool ethereum 0x3687c0f8760371fc1bd1c7bc28695c388cded5a0`
`pnpm run adapter clearpool ethereum 0xb0e6fadc3e16f0f1440d254e095f7b1019ec03db`
`pnpm run adapter clearpool ethereum 0x5a9767e242b352a07e6f5c87efbc3ae228296967`

Feat:Adapter,ClearPool, eth, op, matic

---

src/db/balances.ts
src/handlers/getTokenBalanceChart.ts

feat: balance chart updates

---

.vscode/launch.json
src/adapters/balancer/arbitrum/index.ts
src/adapters/balancer/avalanche/index.ts
src/adapters/balancer/common/balance.ts
src/adapters/balancer/ethereum/index.ts
src/adapters/balancer/gnosis/index.ts
src/adapters/balancer/optimism/index.ts
src/adapters/beethoven-x/common/fBeets.ts
src/adapters/beethoven-x/common/pool.ts
src/adapters/beethoven-x/fantom/index.ts
src/adapters/beethoven-x/index.ts
src/adapters/beethoven-x/optimism/index.ts
src/adapters/index.ts

`pnpm run adapter beethoven-x optimism 0xc181edc719480bd089b94647c2dc504e2700a2b0` 
`pnpm run adapter beethoven-x fantom 0x28aa4f9ffe21365473b64c161b566c3cdead0108`

Feat:Adapter,Beethoven,Op,Ftm

---

src/adapters/silo-finance/arbitrum/index.ts
src/adapters/silo-finance/common/balance.ts
src/adapters/silo-finance/common/pool.ts
src/adapters/silo-finance/ethereum/index.ts

> Fix inaccurate function (shareBalance -> assetBalance), add missing contracts, split groups, add MCR

Feat:Adapter,Silo-Finance,Arb/Eth

---

src/adapters/equilibria/arbitrum/index.ts
src/adapters/equilibria/common/lock.ts
src/adapters/equilibria/common/pool.ts

> Fix equilbria rewards on arb (arb incentives) and add missing locker

Fix,Equilibria,Missing Locker,Missing Rewards

---

.vscode/launch.json
src/adapters/aura/optimism/index.ts
src/adapters/beethoven-x/fantom/index.ts
src/adapters/beethoven-x/optimism/index.ts
src/adapters/equilibria/common/pool.ts
src/adapters/index.ts
src/adapters/liquid-driver/fantom/index.ts
src/adapters/proxy/index.ts
src/adapters/proxy/polygon/index.ts

`pnpm run adapter proxy polygon 0x015cee3ab6d03267b1b2c05d2ac9e2250af5268d`

feat:Adapter,Proxy,polygon

---

src/adapters/keom-protocol/polygon/index.ts

Fix matic addr

---

src/adapters/tetu/polygon/index.ts
src/adapters/tetu/polygon/locker.ts

`pnpm run adapter tetu polygon 0x36cc7b13029b5dee4034745fb4f24034f3f2ffc6`

Update,Tetu,Lock on polygon

---

.vscode/launch.json
src/adapters/gitcoin/ethereum/balance.ts
src/adapters/gitcoin/ethereum/index.ts
src/adapters/gitcoin/index.ts
src/adapters/index.ts

`pnpm run adapter gitcoin ethereum 0x8a83716acd66d9e1fb18c9b79540b72e04f80ac0
`

Feat:Adapter,Gitcoin,Ethereum

---

src/adapters/prisma-finance/ethereum/contract.ts
src/adapters/prisma-finance/ethereum/index.ts

> Small refacto, add missing contracts

Update, Prisma

---

src/adapters/gmx/common/balances.ts
src/adapters/gmx/common/contracts.ts

Fix,Adapter,GMX, glp underlyings

---

src/db/clickhouse.ts

feat: ch settings max_threads

---

.vscode/launch.json
src/adapters/idle/common/pool.ts
src/adapters/idle/common/tranche.ts
src/adapters/idle/ethereum/index.ts
src/adapters/idle/index.ts
src/adapters/idle/optimism/index.ts
src/adapters/index.ts
src/lib/stake.ts

`pnpm run adapter-balances idle-finance ethereum 0x06b45f7844ab84f93f38e207777a7a76759dc143`
`pnpm run adapter-balances idle-finance ethereum 0xfb3bd022d5dacf95ee28a6b07825d4ff9c5b3814`

Feat:Adapter,Idle,Ethereum,Optimism

---

.vscode/launch.json
src/adapters/clever/ethereum/balance.ts
src/adapters/clever/ethereum/contract.ts
src/adapters/clever/ethereum/farm.ts
src/adapters/clever/ethereum/index.ts
src/adapters/clever/ethereum/stake.ts
src/adapters/clever/index.ts
src/adapters/index.ts

`pnpm run adapter-balances clever ethereum 0x0056d1fd2ca3c0f3a7b6ed6cdd1f1f104b4bf9a9`

Feat:Adapter,Clever

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/protectorate-protocol/ethereum/balance.ts
src/adapters/protectorate-protocol/ethereum/index.ts
src/adapters/protectorate-protocol/index.ts

`pnpm run adapter-balances protectorate-protocol ethereum 0x29a031f1f19a04f341bc941fc84c093f22334a9c`
`pnpm run adapter-balances protectorate-protocol ethereum 0x2fdf502ac2f054d5983a4a4ba916b2f2d4056685`

feat:Adapter,Protectorate

---

src/adapters/frax-finance/arbitrum/index.ts
src/adapters/frax-finance/arbitrum/locker.ts

`pnpm run adapter-balances frax-finance arbitrum 0x7bfee91193d9df2ac0bfe90191d40f23c773c060`

Update,Frax,Lock on arbitrum

---

src/adapters/abracadabra/arbitrum/index.ts
src/adapters/abracadabra/common/farm.ts

`pnpm run adapter-balances abracadabra arbitrum 0xbdfa4f4492dd7b7cf211209c4791af8d52bf5c50`

Update,Abracadabra, add missing farm on arbitrum

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/treasuredao/arbitrum/balance.ts
src/adapters/treasuredao/arbitrum/index.ts
src/adapters/treasuredao/arbitrum/locker.ts
src/adapters/treasuredao/arbitrum/pool.ts
src/adapters/treasuredao/index.ts

`pnpm run adapter treasuredao arbitrum 0xa4c8d9e4ec5f2831701a81389465498b83f9457d`
`pnpm run adapter treasuredao arbitrum 0xbed9322ff037e6b7c8b2983188ae810ce0b72be2`

feat:Adapter,Treasuredao

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/locus-finance/arbitrum/index.ts
src/adapters/locus-finance/common/balance.ts
src/adapters/locus-finance/common/pool.ts
src/adapters/locus-finance/ethereum/index.ts
src/adapters/locus-finance/index.ts

`pnpm run adapter locus-finance arbitrum 0xf793859ec763477ee2f282186ebb2fb2e6a71bba`
`pnpm run adapter locus-finance arbitrum 0x423bf3038eaee9cb3880dddc44b8aaa543aa5b4a`

Feat,adapter,Locus finance

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/steer-protocol/arbitrum/index.ts
src/adapters/steer-protocol/avalanche/index.ts
src/adapters/steer-protocol/base/index.ts
src/adapters/steer-protocol/bsc/index.ts
src/adapters/steer-protocol/common/balance.ts
src/adapters/steer-protocol/common/pool.ts
src/adapters/steer-protocol/index.ts
src/adapters/steer-protocol/linea/index.ts
src/adapters/steer-protocol/optimism/index.ts
src/adapters/steer-protocol/polygon/index.ts

`pnpm run adapter steer-protocol arbitrum 0xa969995755ffcf6cc8a8448ea82b7723f273931c`
`pnpm run adapter steer-protocol polygon 0xe26b4edeb70ac8723077e2637b214eb850561e99`

feat:Adapter,Steer-protocol

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/shell-protocol/arbitrum/balance.ts
src/adapters/shell-protocol/arbitrum/index.ts
src/adapters/shell-protocol/index.ts

`pnpm run adapter shell-protocol arbitrum 0x0cb736ea2ad425221c368407caafdd323b7bdc83`

feat:Adapter,Shell,arb

---

.vscode/launch.json
src/adapters/frax-finance/arbitrum/locker.ts
src/adapters/index.ts
src/adapters/opium/ethereum/balance.ts
src/adapters/opium/ethereum/index.ts
src/adapters/opium/index.ts
src/lib/pricePerShare.ts

`pnpm run adapter opium ethereum 0x47441bd9fb3441370cb5b6c4684a0104353aec66`
`pnpm run adapter opium ethereum 0x65402c084f79d698e17f32617f6c4198751dc5a0`

Lib pricePerShare + Opium adapter

---

src/db/history.ts
src/handlers/getHistory.ts
src/lib/fmt.ts

- change time interval inclusivity
- change default values to hit current partition

feat: history time interval [from,to[

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/metronome/common/balance.ts
src/adapters/unitus/arbitrum/index.ts
src/adapters/unitus/bsc/index.ts
src/adapters/unitus/common/lend.ts
src/adapters/unitus/common/staker.ts
src/adapters/unitus/ethereum/index.ts
src/adapters/unitus/ethereum/lock.ts
src/adapters/unitus/ethereum/stake.ts
src/adapters/unitus/index.ts
src/adapters/unitus/optimism/index.ts
src/adapters/unitus/polygon/index.ts
src/lib/pricePerShare.ts

`pnpm run adapter unitus optimism 0x4f27eb908eaadfea04f6b66847faabaeb45ecb15`

feat:Adapter,Unitus(dForce)

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/mugenfinance/arbitrum/balance.ts
src/adapters/mugenfinance/arbitrum/index.ts
src/adapters/mugenfinance/index.ts

`pnpm run adapter mugenfinance arbitrum 0x14350e8ab1f3cdf72010fe743a0a05e44902b16e`

feat:Adapter,MugenFinance

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/spartadex/arbitrum/index.ts
src/adapters/spartadex/index.ts
src/lib/pricePerShare.ts

`pnpm run adapter spartadex arbitrum 0xf9ef048a772f821afd5fb3ce605eabedafbfe52a`

Feat:Adapter,SpartaDex

---

serverless.yml
src/db/gas.ts
src/handlers/getGasChart.ts
src/handlers/getGasUsed.ts
src/handlers/getTokenBalanceChart.ts

fix: gas chart

---

serverless.yml
src/db/contracts.ts
src/handlers/getTrendingContracts.ts
src/lib/chains.ts

feat: trending contracts endpoint

---

serverless.yml
src/db/tokensTransfers.ts
src/handlers/getLatestTokensTransfers.ts

feat: get latest tokens transfers

---

serverless.yml
src/db/yields.ts
src/handlers/getTokenYields.ts

feat: token yields

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/renzo/ethereum/index.ts
src/adapters/renzo/index.ts

`pnpm run adapter-balances renzo ethereum 0xf50fa91cd7f63c94b4308e50676d2e9247cbb8a4`

Feat:Renzo,Adapter,Ethereum

---

scripts/get-abi-sig.ts

feat: get ABI sig script

---

package.json
scripts/get-contract-info.ts
src/db/contracts.ts

- fix multi-address mapping
- add `adapter_id` field

fix: get-contract-info script

---

src/adapters/ipor/ethereum/farm.ts
src/adapters/ipor/ethereum/index.ts

pnpm run adapter-balances ipor ethereum 0x7bfee91193d9df2ac0bfe90191d40f23c773c060

Fix:Ipor,PricePerFullShare

---

src/adapters/yearn-finance/common/balance.ts
src/adapters/yearn-finance/ethereum/farm.ts
src/adapters/yearn-finance/ethereum/index.ts

`pnpm run adapter-balances yearn-finance ethereum 0xf750162fd81f9a436d74d737ef6ee8fc08e98220`
`pnpm run adapter-balances yearn-finance ethereum 0x7bfee91193d9df2ac0bfe90191d40f23c773c060`

Update,Yearn, ethereum missing farms

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/interport-finance/common/farm.ts
src/adapters/interport-finance/common/masterChef.ts
src/adapters/interport-finance/common/vest.ts
src/adapters/interport-finance/ethereum/index.ts
src/adapters/interport-finance/index.ts

`pnpm run adapter interport-finance ethereum 0x31d3243cfb54b34fc9c73e1cb1137124bd6b13e1`

Feat:Adapter,Interport,Ethereum

---

src/adapters/makerdao/ethereum/balances.ts
src/adapters/makerdao/ethereum/farm.ts
src/adapters/makerdao/ethereum/index.ts

`pnpm run adapter makerdao ethereum 0x07499c08287a6cd6514cace69100916c67631dc7`

Update,Maker,add missing yield (2G TVL)

---

.vscode/launch.json
src/adapters/dyad/ethereum/balance.ts
src/adapters/dyad/ethereum/index.ts
src/adapters/dyad/index.ts
src/adapters/index.ts

`pnpm run adapter-balances dyad ethereum 0x7bfee91193d9df2ac0bfe90191d40f23c773c060`

Feat:Adapter,Dyad (CDP), ethereum

---

src/db/yields.ts

fix: https://github.com/llamafolio/llamafolio-api/issues/1177

fix: token yields underlyings

---

.vscode/launch.json
src/adapters/gogopool/avalanche/balance.ts
src/adapters/gogopool/avalanche/index.ts
src/adapters/gogopool/index.ts
src/adapters/index.ts

`pnpm run adapter gogopool avalanche 0xff4606bd3884554cdbdabd9b6e25e2fad4f6fc54`
`pnpm run adapter gogopool avalanche 0x833afa7db3567d8be01d43ae03a0ae229de36a04`

feat:Adapter,gogopool,avalanche

---

.vscode/launch.json
src/adapters/cyclone/bsc/index.ts
src/adapters/cyclone/common/balance.ts
src/adapters/cyclone/common/pool.ts
src/adapters/cyclone/ethereum/index.ts
src/adapters/cyclone/index.ts
src/adapters/cyclone/polygon/index.ts
src/adapters/index.ts

` pnpm run adapter cyclone ethereum 0x06bb952b3ae7209abdbdbb7a0b6757fa6655c189`
`pnpm run adapter cyclone bsc 0xa3d37389d8e22750ccf6c833d3d25b2a2a248319`

Feat:Adapter,Cyclone

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/vault-tech/ethereum/index.ts
src/adapters/vault-tech/ethereum/vault.ts
src/adapters/vault-tech/index.ts

`pnpm run adapter vault-tech ethereum 0xd605b50723a73e8b6f5b25eea2a29462d14c84e4`
`pnpm run adapter vault-tech ethereum 0x9f2022c9b3bd047915a04aeab263528c53c4ce2d`

Feat:adapter,Vault-tech, ethereum

---

.vscode/launch.json
src/adapters/bloom/ethereum/index.ts
src/adapters/bloom/index.ts
src/adapters/index.ts

`pnpm run adapter bloom ethereum 0xa1486dae9f01e7da3bd8efbd12af0e1be1c73b60`

Feat:Adapter,Bloom,Ethereum

---

scripts/update-coingecko-coins.ts
serverless.yml
src/db/tokens.ts
src/handlers/updateCoingeckoCoins.ts
src/lib/lambda.ts

feat: scheduled update coingecko coins

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/stabl.fi/index.ts
src/adapters/stabl.fi/polygon/balance.ts
src/adapters/stabl.fi/polygon/index.ts

`pnpm run adapter-balances stabl.fi polygon 0x8fb20c72139b2a971ab814503d61111349f8cc78`

Feat:Adapter,Stabl.fi

---

.vscode/launch.json
src/adapters/affine-defi/index.ts
src/adapters/affine-defi/polygon/balance.ts
src/adapters/affine-defi/polygon/contract.ts
src/adapters/affine-defi/polygon/index.ts
src/adapters/index.ts

`pnpm run adapter-balances affine-defi polygon 0x90e06d2d9705c181bad2a4e7c3dca13631a6f479`

Feat:Adapter,Affine-Defi,Polygon

---

package.json
pnpm-lock.yaml
src/lib/erc20.ts

bump: viem 2.2.0

---

.vscode/launch.json
src/adapters/avalaunch/avalanche/index.ts
src/adapters/avalaunch/avalanche/masterChef.ts
src/adapters/avalaunch/index.ts
src/adapters/index.ts

`pnpm run adapter avalaunch avalanche 0xc42083a41dd6831477a5dab9ff61cbeb0f9b7165`

Feat:Adapter,Avalaunch

---

.vscode/launch.json
src/adapters/arpa-staking/ethereum/balance.ts
src/adapters/arpa-staking/ethereum/index.ts
src/adapters/arpa-staking/index.ts
src/adapters/index.ts

`pnpm run adapter arpa-staking ethereum 0xf51f1cf8ae3b3a24d926d219b76d29d4df019c1b`

Feat:Adapter,Arpa,Ethereum

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/yieldflow/ethereum/balance.ts
src/adapters/yieldflow/ethereum/index.ts
src/adapters/yieldflow/ethereum/pool.ts
src/adapters/yieldflow/index.ts

`pnpm run adapter-balances yieldflow ethereum 0x5c2ba11add6de4a0ad1af367a8bf1e2cf8c3829b`

Feat:Adapter,YieldFlow,Ethereum

---

serverless.yml
src/db/protocols.ts
src/handlers/getProtocolContracts.ts

feat: protocol contracts

---

src/adapters/balancer/ethereum/locker.ts

`pnpm run adapter-balances balancer ethereum 0x36cc7b13029b5dee4034745fb4f24034f3f2ffc6`

Fix, veEscrow Math on balancer

---

src/adapters/aura/common/balance.ts

> add missing rewards on stkAura

Fix, stkAura rewards

---

.vscode/launch.json
src/adapters/apwine/ethereum/index.ts
src/adapters/apwine/index.ts
src/adapters/index.ts

`pnpm run adapter-balances apwine ethereum 0x0edefa91e99da1eddd1372c1743a63b1595fc413`

feat:Adapter,Apwine,ethereum

---

.vscode/launch.json
src/adapters/firebot/index.ts
src/adapters/firebot/polygon/balance.ts
src/adapters/firebot/polygon/index.ts
src/adapters/index.ts

`pnpm run adapter firebot polygon 0xe20e046b230a5530438d32abfbcc3e61d7670234`
`pnpm run adapter firebot polygon 0x9e43b71d2483dff3ed2a369d92a13146c836b100`

Feat:Adapter,Firebot,polygon

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/integral/arbitrum/index.ts
src/adapters/integral/ethereum/index.ts
src/adapters/integral/ethereum/stake.ts
src/adapters/integral/index.ts

`pnpm run adapter integral ethereum 0xf282fdd49412c151629b54351cd3a6831628d348`
`pnpm run adapter integral ethereum 0x51db4f9ce143a0ab81eebdca99bab8e4d2479d45`

Feat:Adapter, Integral

---

scripts/update-protocols.ts
src/adapters/integral/index.ts
src/handlers/updateProtocols.ts
src/lib/protocols.ts

- remove unused `color` field
- avoid duplicates in protocols table

fix: update protocols no duplicates

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/swapbased/base/balance.ts
src/adapters/swapbased/base/index.ts
src/adapters/swapbased/base/masterChef.ts
src/adapters/swapbased/index.ts

`pnpm run adapter-balances swapbased base 0x7b59c390ce9b6425915db386e6e41ec7ad6733c0`
`pnpm run adapter-balances swapbased base 0xf368d43f148e1803ec793670183b0ca6a07d3898`

Feat:Adapter,SwapBased,base

---

src/adapters/rocketswap-base/base/index.ts
src/adapters/rocketswap-base/index.ts

`pnpm run adapter rocketswap-base base 0x06c9d5dc7a3618d17eb44794574c0713bd82fffd
`

Feat:Adapter,RocketSwap,Base

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/scale/base/balance.ts
src/adapters/scale/base/contract.ts
src/adapters/scale/base/index.ts
src/adapters/scale/base/locker.ts
src/adapters/scale/index.ts

`pnpm run adapter scale base 0x74293a57d7f6b9f6c5580ce50aae3f10a0a09c56`
` pnpm run adapter scale base 0x804aed5e9835dc56419695f2d1cf877ae0336579`
`pnpm run adapter scale base 0xf368d43f148e1803ec793670183b0ca6a07d3898`

Feat:Adapter,Scale,Base

---

scripts/update-protocols-tokens.ts
serverless.yml
src/db/tokens.ts
src/handlers/updateProtocolsTokens.ts
src/lib/lambda.ts

feat: scheduled update protocols tokens

---

src/adapters/paladin-warlord/ethereum/balance.ts
src/adapters/paladin-warlord/ethereum/index.ts
src/adapters/paladin-warlord/index.ts

feat: paladin warlord adapter

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/tholgar/ethereum/balance.ts
src/adapters/tholgar/ethereum/index.ts
src/adapters/tholgar/index.ts

feat: tholgar adapter

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/vapordex/avalanche/index.ts
src/adapters/vapordex/index.ts

` pnpm run adapter vapordex avalanche 0x17427af0f2e0ed27856c3288bb902115467e2540`

feat:Adapter,Vapordex,Avalanche

---

.vscode/launch.json
src/adapters/gambit-trade/arbitrum/balance.ts
src/adapters/gambit-trade/arbitrum/index.ts
src/adapters/gambit-trade/arbitrum/stake.ts
src/adapters/gambit-trade/index.ts
src/adapters/index.ts

`pnpm run adapter gambit-trade arbitrum 0xd8ecbc0916d1ec397ec31c94913249b0d031a6a6`

Feat:Adapter,Gambit,Arbitrum

---

src/adapters/glori-finance/arbitrum/index.ts
src/adapters/glori-finance/arbitrum/masterChef.ts
src/adapters/glori-finance/index.ts

`pnpm run adapter glori-finance arbitrum 0x762cc27ea6b7416cb4ddb955b8a8ca3afb7c255d`

Feat:Adapter,Glori,Arbitrum

---

src/db/yields.ts
src/handlers/getTokenYields.ts

allow to pull all yields at once

feat: token yields optional pagination

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/morpho-blue/ethereum/balance.ts
src/adapters/morpho-blue/ethereum/contract.ts
src/adapters/morpho-blue/ethereum/index.ts
src/adapters/morpho-blue/index.ts

`pnpm run adapter morpho-blue ethereum 0xf6853c77a2452576eae5af424975a101ffc47308`

feat:Adapter,MorphoBlue,Ethereum

---

.vscode/launch.json
src/adapters/defi-swap/ethereum/index.ts
src/adapters/defi-swap/ethereum/stake.ts
src/adapters/defi-swap/index.ts
src/adapters/index.ts

`pnpm run adapter-balances defi-swap ethereum 0xd57854477b0ad859cd887fce30be3cb3b25bc5fe`

Feat:Adapter,DefiSwap,Ethereum

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/puffer-finance/ethereum/balance.ts
src/adapters/puffer-finance/ethereum/index.ts
src/adapters/puffer-finance/index.ts

pnpm run adapter-balances puffer-finance ethereum 0x5c2632cedb167609c7f12e9bbfbc5665cfd66d40

Feat:Adapter,Puffer-Finance,Ethereum

---

serverless.yml
src/db/protocols.ts
src/handlers/getProtocolHolders.ts
src/handlers/response.ts
src/lib/fmt.ts

feat: protocols holders early support

---

src/db/protocols.ts
src/handlers/getProtocolHolders.ts

feat: protocols holders last update

---

.gitignore
src/db/protocols.ts
src/handlers/getProtocolHolders.ts

feat: protocol holders share

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/radioshack/avalanche/index.ts
src/adapters/radioshack/bsc/index.ts
src/adapters/radioshack/ethereum/index.ts
src/adapters/radioshack/fantom/index.ts
src/adapters/radioshack/index.ts
src/adapters/radioshack/optimism/index.ts
src/adapters/radioshack/polygon/index.ts

`pnpm run adapter radioshack ethereum 0x2416b578c319346ddf5865d07a701a1e005b67d1`

feat: Adapter,RadioShack

---

src/adapters/uniswap-v3/common/pools.ts

`pnpm run adapter uniswap-v3 ethereum 0x378bcce7235d53bbc3774bff8559191f06e6818e`

Fix uni v3 math

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/peapods-finance/ethereum/index.ts
src/adapters/peapods-finance/ethereum/pool.ts
src/adapters/peapods-finance/index.ts

`pnpm run adapter-balances peapods-finance ethereum 0xc64bc02594ba7f777f26b7a1eec6e6dc4a56362b`

Feat:Adapter, Peapods, Ethereum

---

scripts/create-adapter.ts

`pnpm run create-adapter camelot`

Fix create adapter, wasnt working correctly

---

scripts/delete-adapter.ts
scripts/revalidate-contracts-rec.ts
scripts/revalidate-contracts.ts
serverless.yml
src/db/adapters.ts
src/db/contracts.ts
src/db/protocols.ts
src/db/tokens.ts
src/handlers/revalidateAdapters.ts
src/lib/adapter.ts

feat: update adapter contracts revalidation 

---

.vscode/launch.json
package.json
pnpm-lock.yaml
scripts/build-adapters.ts
scripts/revalidate-contracts-rec.ts
scripts/update-adapter-balances-prices.ts
scripts/update-adapter-balances.ts
scripts/utils/adapter-balances-job.ts
src/adapters/blast/ethereum/index.ts
src/adapters/creth2/ethereum/index.ts
src/adapters/crvusd/ethereum/index.ts
src/db/balances.ts
src/db/contracts.ts
src/handlers/getLatestSnapshot.ts
src/handlers/getLatestTokensTransfers.ts
src/handlers/getTokenYields.ts
src/lib/adapter.ts
src/lib/cache.ts
src/lib/call.ts
src/lib/chains.ts
src/lib/ens.ts
src/lib/fmt.ts
src/lib/multicall.ts
src/lib/price.ts
src/lib/type.ts

feat: bulk balance updates

---

.vscode/launch.json
src/adapters/horiza/arbitrum/index.ts
src/adapters/horiza/arbitrum/locker.ts
src/adapters/horiza/index.ts
src/adapters/index.ts

`pnpm run adapter horiza arbitrum 0x41bc7d0687e6cea57fa26da78379dfdc5627c56d`
`pnpm run adapter horiza arbitrum 0x85cac54dacedf5d0cd619ca80631b34b1a0055e9`

Feat:Horiza,Arbitrum (ve3,3, ramses fork)

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/kommunitas/arbitrum/index.ts
src/adapters/kommunitas/common/locker.ts
src/adapters/kommunitas/index.ts
src/adapters/kommunitas/polygon/index.ts

`pnpm run adapter kommunitas polygon 0x83a8171f1c6240baaa6bf46ab9cb2bc794f1c29f`

Kommunitas

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/virtuswap/index.ts
src/adapters/virtuswap/polygon/balance.ts
src/adapters/virtuswap/polygon/index.ts

`pnpm run adapter virtuswap polygon 0x9c58a2b79cd054442d5970b925637b9e88e7ecc2`
`pnpm run adapter virtuswap polygon 0x12fe17773a20f6ed00cddb43e24ac9183f6e58ab`

feat:Adapter, Virtuswap, polygon

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/swaap/arbitrum/index.ts
src/adapters/swaap/common/pool.ts
src/adapters/swaap/ethereum/index.ts
src/adapters/swaap/index.ts
src/adapters/swaap/polygon/index.ts

`pnpm run adapter swaap ethereum 0x8bebedb0539cc416f76881e957f15575edde23dd`
`pnpm run adapter swaap arbitrum 0xa8b77e916aa5f4ddf96f25f7d0725f8a8240971b`

Feat:Adapter,Swaap

---

scripts/get-tokens.ts
scripts/run-adapter-balances.ts
scripts/run-adapter.ts
scripts/test-multicall.ts
scripts/update-adapter-balances.ts
scripts/update-missing-tokens.ts
scripts/update-tokens.ts
src/adapters/atlas-usv/polygon/vest.ts
src/adapters/fantohm/fantom/vest.ts
src/adapters/gyro/bsc/vester.ts
src/adapters/redacted/ethereum/vest.ts
src/adapters/wallet/index.ts
src/handlers/getBalancesTokens.ts
src/handlers/getHistory.ts
src/handlers/getToken.ts
src/handlers/getTokenBalanceChart.ts
src/handlers/updateBalances.ts
src/handlers/updateProtocolsTokens.ts
src/labels/ens/index.ts
src/lib/adapter.ts
src/lib/balance.ts
src/lib/call.ts
src/lib/chains.ts
src/lib/erc20.ts
src/lib/multicall.ts

fix: https://github.com/llamafolio/llamafolio-api/issues/1263
allows us to change the RPC client config based on the execution context

feat: move rpc client to context

---

src/lib/erc20.ts

Erc20Fixes, wallet

---

.vscode/launch.json
src/adapters/blueberry-lend/ethereum/balance.ts
src/adapters/blueberry-lend/ethereum/index.ts
src/adapters/blueberry-lend/ethereum/pool.ts
src/adapters/blueberry-lend/index.ts
src/adapters/index.ts

`pnpm run adapter blueberry-lend ethereum 0xbdfa4f4492dd7b7cf211209c4791af8d52bf5c50`

Feat:Adapter,BlueBerry,Ethereum

---

src/adapters/perennial/arbitrum/balance.ts
src/adapters/perennial/arbitrum/index.ts

` pnpm run adapter perennial arbitrum 0x614d98a57a5d879d717152de0690ed2b04562ade`

Update, Perennial_v2, stake

---

package.json
pnpm-lock.yaml
scripts/update-adapter-balances.ts
src/lib/chains.ts

higher retry strategy for snapshot script

feat: modular RPC config

---

scripts/update-adapter-balances.ts
scripts/utils/adapter-balances-job.ts
src/db/contracts.ts
src/lib/adapter.ts
src/lib/balance.ts

- capture errors
- ignore snapshot on failed adapters (until fixed)
- run all adapters

feat: snapshot adapters balances

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/meta-pool/ethereum/balance.ts
src/adapters/meta-pool/ethereum/index.ts
src/adapters/meta-pool/index.ts

`pnpm run adapter meta-pool ethereum 0x49a323cc2fa5f9a138f30794b9348e43065d8da2`

feat:Adapter,Meta-pool,ethereum, lst

---

.vscode/launch.json
src/adapters/gammaswap/arbitrum/index.ts
src/adapters/gammaswap/arbitrum/pool.ts
src/adapters/gammaswap/index.ts
src/adapters/index.ts

`pnpm run adapter gammaswap arbitrum 0x64e288f022d9d1e9a8dfac32e36e2d0b71a8bc0f`
`pnpm run adapter gammaswap arbitrum 0x63c531ffed7e17f8adca4ed490837838f6fa1b66`

Feat:Adapter,Gammaswap,dexes

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/rhino.fi/ethereum/balance.ts
src/adapters/rhino.fi/ethereum/index.ts
src/adapters/rhino.fi/index.ts
src/adapters/vector-reserve/ethereum/index.ts

`pnpm run adapter rhino.fi ethereum 0x5d22045daceab03b158031ecb7d9d06fad24609b`

feat:Adapter,Rhino.fi,ethereum

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/kyberswap/arbitrum/index.ts
src/adapters/kyberswap/avalanche/index.ts
src/adapters/kyberswap/base/index.ts
src/adapters/kyberswap/bsc/index.ts
src/adapters/kyberswap/common/pair.ts
src/adapters/kyberswap/common/stake.ts
src/adapters/kyberswap/ethereum/index.ts
src/adapters/kyberswap/fantom/index.ts
src/adapters/kyberswap/index.ts
src/adapters/kyberswap/linea/index.ts
src/adapters/kyberswap/optimism/index.ts
src/adapters/kyberswap/polygon/index.ts

`pnpm run adapter kyberswap ethereum 0x36cc7b13029b5dee4034745fb4f24034f3f2ffc6`
`pnpm run adapter kyberswap ethereum 0x6f8603057ec7f82205e931a85f52eaba75a8f663`

feat:Adapter,Kyberswap

---

.vscode/launch.json
src/adapters/derivadex/ethereum/balance.ts
src/adapters/derivadex/ethereum/index.ts
src/adapters/derivadex/index.ts
src/adapters/index.ts

`pnpm run adapter derivadex ethereum 0xa019a71f73922f5170031f99efc37f31d3020f0b`

Feat:Adapter,DerivaDex,ethereum

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/perion/ethereum/balance.ts
src/adapters/perion/ethereum/index.ts
src/adapters/perion/index.ts

`pnpm run adapter perion ethereum 0xa7393d2f073eadd425b254a60e72c464e8fa4c20`

feat:Adapter,Perion,Ethereum

---

src/adapters/equilibria/arbitrum/index.ts
src/adapters/equilibria/common/vest.ts

feat:Update,Equilibria, arbitrum, vest logic

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/pingu-exchange/arbitrum/balance.ts
src/adapters/pingu-exchange/arbitrum/index.ts
src/adapters/pingu-exchange/index.ts

` pnpm run adapter pingu-exchange arbitrum 0x9ef847bb071c155edd6253f5d59f307fd4325e7f`

feat:Adapter,Pingu-exchange, arbitrum

---

src/adapters/silo-finance/arbitrum/index.ts

update, silo-finance, arbitrum

---

.vscode/launch.json
src/adapters/hmx/arbitrum/balance.ts
src/adapters/hmx/arbitrum/contract.ts
src/adapters/hmx/arbitrum/index.ts
src/adapters/hmx/arbitrum/vest.ts
src/adapters/hmx/index.ts
src/adapters/index.ts

`pnpm run adapter hmx arbitrum 0x10aa41ed6463357b76f6c53e07473155b52838e0`

feat:Adapter,Hmx,arbitrum

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/qidao/arbitrum/index.ts
src/adapters/qidao/avalanche/index.ts
src/adapters/qidao/base/index.ts
src/adapters/qidao/common/balance.ts
src/adapters/qidao/common/vault.ts
src/adapters/qidao/common/yields.ts
src/adapters/qidao/ethereum/index.ts
src/adapters/qidao/fantom/index.ts
src/adapters/qidao/index.ts
src/adapters/qidao/linea/index.ts
src/adapters/qidao/moonbeam/index.ts
src/adapters/qidao/optimism/index.ts
src/adapters/qidao/polygon/index.ts

`pnpm run adapter qidao base 0x9eb408e53dfa0c877b65bbe874de81247212380e`
`pnpm run adapter qidao polygon 0x7dda5e1a389e0c1892caf55940f5fce6588a9ae0`

feat:Adapter,Qidao

---

src/lib/adapter.ts

revalidate contracts split big batch into smaller chunks

fix: revalidate contracts slice chunks

---

src/adapters/morpho-blue/ethereum/asset.ts
src/adapters/morpho-blue/ethereum/balance.ts
src/adapters/morpho-blue/ethereum/index.ts
src/adapters/morpho-blue/ethereum/lend.ts

update, morpho-blue, lend, add new farms

---

src/lib/chains.ts
src/lib/protocols.ts

some addresses are prefixed with the chain name

fix: protocols token address maybe chain prefix

---

src/db/protocols.ts
src/handlers/getProtocols.ts
src/lib/protocols.ts

cross-reference adapters table to get supported chains (we may not support as many chains as DefiLlama)

fix: get protocols filter only supported chains

---

src/db/lendBorrow.ts
src/handlers/getTokenBorrow.ts
src/handlers/getTokenLend.ts

fix: lend/borrow types + caching

---

src/lib/slack.ts

Slack mess env

---

src/adapters/centrifuge/ethereum/balance.ts
src/adapters/centrifuge/ethereum/pool.ts

`pnpm run adapter centrifuge ethereum  0x1bd5d6e5d95393a3175c56683b2cb9ddb3188fc1`

fix_centrifuge

---

src/db/contracts.ts

fix: wallet interactions group by

---

package.json
pnpm-lock.yaml

bump: viem 2.7.16

---

src/adapters/reflexer/ethereum/farm.ts

`pnpm run adapter-balances reflexer ethereum 0xe207f98c7ad7f7b3895d4a105453e898771e2067`

fix_reflexer, handler if fetch is nullish

---

src/adapters/alchemix/common/transmuter-v2.ts

`pnpm run adapter-balances alchemix ethereum 0x0d0db6402196fb090cd251a1503b5688a30a6116`

Fix alchemix

---

src/handlers/updateBalances.ts

feat: update balances reuse rpc client per chain

---

src/adapters/compound-v3/arbitrum/index.ts
src/adapters/compound-v3/base/index.ts
src/adapters/compound-v3/common/asset.ts
src/adapters/compound-v3/common/balance.ts
src/adapters/compound-v3/ethereum/index.ts
src/adapters/compound-v3/polygon/index.ts

Fix, compound-v3 duplicate lendBalances

---

src/db/balances.ts

Fix: https://github.com/llamafolio/llamafolio-api/pull/1332

fix: GET balances query

---

src/adapters/compound-v3/common/asset.ts

feat: Compound, Hfs

---

src/adapters/magpie/bsc/index.ts
src/adapters/magpie/common/cakepie.ts

`pnpm run adapter-balances magpie bsc 0x3e8734ec146c981e3ed1f6b582d447dde701d90c`

Update, Magpie: add cakepie pools

---

src/adapters/dhedge/common/balance.ts

fix_dHedge number

---

README.md
src/adapters/pendle/common/balance.ts
src/adapters/pendle/common/pool.ts

update, pendle

---

src/db/protocols.ts

Fix: https://github.com/llamafolio/llamafolio-api/issues/1342

fix: GET protocols uniq chains

---

src/adapters/across/ethereum/v2/balance.ts

across change lp to farm

---

src/adapters/balancer/arbitrum/index.ts
src/adapters/balancer/avalanche/index.ts
src/adapters/balancer/common/balance.ts
src/adapters/balancer/common/pool.ts
src/adapters/balancer/ethereum/index.ts
src/adapters/balancer/gnosis/index.ts
src/adapters/balancer/polygon/index.ts

`pnpm run adapter-balances balancer ethereum 0xaf52695e1bb01a16d33d7194c28c42b10e0dbec2`

Update, balancer, rewards

---

src/adapters/balancer/common/balance.ts
src/lib/balance.ts

Balancer small fixes

---

src/adapters/blueberry-lend/ethereum/balance.ts
src/adapters/blueberry-lend/ethereum/index.ts

`pnpm run adapter-balances blueberry-lend ethereum 0x854f1269b659a727a2268ab86ff77cfb30bfb358`

blueberry-lend farming part

---

package.json
scripts/update-adapter.ts
src/adapters/virtuswap/arbitrum/index.ts
src/adapters/virtuswap/index.ts

add new script run update-adapter

---

src/handlers/getBalancesTokens.ts
src/handlers/updateBalances.ts

feat: getBalancesTokens timeout

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/zircuit-staking/ethereum/balance.ts
src/adapters/zircuit-staking/ethereum/index.ts
src/adapters/zircuit-staking/index.ts
src/lib/slack.ts

`pnpm run adapter-balances zircuit-staking ethereum 0x78404d447139901fe677918629ce08173b505538`

reactive slack message + Adapter Zircuit restaking

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/merlins-seal/arbitrum/index.ts
src/adapters/merlins-seal/common/balance.ts
src/adapters/merlins-seal/ethereum/index.ts
src/adapters/merlins-seal/index.ts

`pnpm run adapter merlins-seal ethereum 0xd8da197df43f8df574bf1963c04fa55eada3c9e9`
`pnpm run adapter merlins-seal ethereum 0x69dd643dbee39fe3a8ba45c6df7c01f849aec4f8`

feat:Adapter, Merlins-Seal

---

.vscode/launch.json
src/adapters/blackrockfund/ethereum/index.ts
src/adapters/blackrockfund/ethereum/masterChef.ts
src/adapters/blackrockfund/index.ts
src/adapters/index.ts

`pnpm run adapter blackrockfund ethereum 0x9ab73dcfcc4705bcecb4d6afac1048eef1471d30`

feat:Adapter,BlackRockFund

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/tensorplex/ethereum/balance.ts
src/adapters/tensorplex/ethereum/index.ts
src/adapters/tensorplex/index.ts

`pnpm run adapter tensorplex ethereum 0x5744182c85aaa2a7818d1b2add3c452d89933c2e`

feat:Adapter,Tensorplex

---

.vscode/settings.json
src/adapters/fluid/ethereum/balance.ts
src/adapters/fluid/ethereum/index.ts
src/adapters/fluid/ethereum/pool.ts
src/adapters/fluid/index.ts

`pnpm run adapter fluid ethereum 0x267ed5f71ee47d3e45bb1569aa37889a2d10f91e`
`pnpm run adapter fluid ethereum yield_0x8d25c177bcd1a9ff4f8fd7361b37ef3d071b4e74`

feat:Adapter,Fluid, ethereum

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/infusion/base/index.ts
src/adapters/infusion/index.ts

`pnpm run adapter-balances infusion base 0x1fd3bd8c196dd401562d7cbdaa673ae8b5054c70`

feat:Adapter,Infusion,Base

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/openxswap/index.ts
src/adapters/openxswap/optimism/balance.ts
src/adapters/openxswap/optimism/index.ts
src/adapters/openxswap/optimism/masterChef.ts

`pnpm run adapter-balances openxswap optimism 0x6b479f4bcf0321c370d266b592fd44eb0fc47ca8`

feat:Adapter, openxswap

---

src/adapters/copra-finance/arbitrum/balance.ts
src/adapters/copra-finance/arbitrum/index.ts
src/adapters/copra-finance/arbitrum/pool.ts
src/adapters/copra-finance/index.ts

`pnpm run adapter copra-finance arbitrum 0x9c38d97c8f143f6855bf673b3a080137c3f34958`

feat:Adapter,Copra-finance

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/neopin-pool/ethereum/index.ts
src/adapters/neopin-pool/index.ts
src/adapters/neopin-pool/polygon/index.ts

pnpm run adapter-balances neopin-pool ethereum 0x22ef8e0967927178e88c32c0b18ece4685efeee4

feat:Adapter,Neopin-Pool

---

.vscode/launch.json
src/adapters/augury-finance/index.ts
src/adapters/augury-finance/polygon/index.ts
src/adapters/augury-finance/polygon/masterchef.ts
src/adapters/index.ts

pnpm run adapter-balances augury-finance polygon 0xb4d9bfac70c046801811c7dcc32958d67b78da1f

feat:Adapter,AuguryFinance

---

src/adapters/vulcandex/index.ts
src/adapters/vulcandex/polygon/index.ts

pnpm run adapter-balances vulcandex polygon 0xd454732667d2e70bcff577d475a75a9f20ee265b

feat:Adapter,VulcanDex

---

.vscode/launch.json
src/adapters/citadao/ethereum/balance.ts
src/adapters/citadao/ethereum/index.ts
src/adapters/citadao/index.ts
src/adapters/index.ts

`pnpm run adapter citadao ethereum 0xd0488b913082d307c978d22d8d5e445a76e7f94b`

feat:Adapter,Citadao,Ethereum

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/mover/ethereum/balance.ts
src/adapters/mover/ethereum/index.ts
src/adapters/mover/index.ts

`pnpm run adapter mover ethereum 0x00a04f3ff5f05234c704414dc18700bbff17a04f`
`pnpm run adapter mover ethereum 0xef8cc7f23a12d5346cb1beb0dfc92919af4b11ae`

feat:Adapter,Mover,Ethreum

---

package.json
pnpm-lock.yaml

Wait https://github.com/llamafolio/llamafolio-tokens/pull/54

chore: bump llamafolio-tokens 0.1.108

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/zharta/ethereum/balance.ts
src/adapters/zharta/ethereum/contract.ts
src/adapters/zharta/ethereum/index.ts
src/adapters/zharta/index.ts

`pnpm run adapter-balances zharta ethereum 0x40fef8e0a18eb5326f91a865bf016f642358de80`

feat:Adapter,Zharta,ethereum

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/jaypeggers/ethereum/balance.ts
src/adapters/jaypeggers/ethereum/contract.ts
src/adapters/jaypeggers/ethereum/index.ts
src/adapters/jaypeggers/index.ts

`pnpm run adapter-balances jaypeggers ethereum 0xa2dcb52f5cf34a84a2ebfb7d937f7051ae4c697b`

Jaypeggers

---

.vscode/launch.json
src/adapters/bob-fusion/ethereum/balance.ts
src/adapters/bob-fusion/ethereum/index.ts
src/adapters/bob-fusion/index.ts
src/adapters/index.ts

`pnpm run adapter-balances bob-fusion ethereum 0xa75d5997a01451f9665b007ebf22374ea50a5290`

feat:Adapter,Bob-fusion,ethereum

---

.vscode/launch.json
src/adapters/euclid-finance/ethereum/balance.ts
src/adapters/euclid-finance/ethereum/index.ts
src/adapters/euclid-finance/index.ts
src/adapters/index.ts

`pnpm run adapter-balances euclid-finance ethereum 0xf6b0ed4ce3ccf7f65655d61766fb385c787288a1`

feat:Adapter,Euclid-finance,ethereum

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/karak/arbitrum/index.ts
src/adapters/karak/common/balance.ts
src/adapters/karak/common/contract.ts
src/adapters/karak/ethereum/index.ts
src/adapters/karak/index.ts

`pnpm run adapter-balances karak ethereum 0x3cbe564fae0c2e6e08813157ca7e5e80a2b1c62f`
`pnpm run adapter-balances karak arbitrum 0x367b22f56f3b01a4c90d508f9388e9c7ac06ed67`

feat:Adapter,Karak

---

package.json
pnpm-lock.yaml

bump: viem 2.9.19

---

package.json
pnpm-lock.yaml

bump: viem 2.9.25

---

package.json
pnpm-lock.yaml
src/db/clickhouse.ts

bump: clickhouse-client 1.0.1

---

package.json
pnpm-lock.yaml

fix: pnpm packaging

---

src/lib/chains.ts

add rpc for base

---

src/adapters/tholgar/ethereum/index.ts

This PR simply add the second version of Tholgar Finance vault. The token and contract address have changed but the computation method is the same.
Thank you in advance for your review.

Added `tholgar` V2 vault
