src/adapters/uniswap-v3/common/pools.ts

Logic to prevent to display all uniswap LPs on llamafolio
`pnpm run adapter-balances uniswap-v3 ethereum 0xbdfa4f4492dd7b7cf211209c4791af8d52bf5c50`
BEFORE
WITH CLAIM ADDRESS
NOW

Feat: Adapter, Uniswap-v3

---

src/adapters/across/ethereum/v1/balance.ts

Fix decimals on underlyings used by Across to fit with real values on dApp
`pnpm run adapter-balances across ethereum 0xbdfa4f4492dd7b7cf211209c4791af8d52bf5c50`
BEFORE
NOW

Feat: Adapter, Across

---

src/adapters/synthetix/common/farm.ts
src/adapters/synthetix/common/provider/arrakis.ts
src/adapters/synthetix/common/provider/balancer.ts
src/adapters/synthetix/common/provider/curve.ts
src/adapters/synthetix/common/provider/snx.ts
src/adapters/synthetix/common/provider/uniswap.ts
src/adapters/synthetix/ethereum/index.ts
src/adapters/synthetix/index.ts
src/adapters/synthetix/optimism/index.ts

Add different farm providers on SNX (Ethereum + Optimism)
`pnpm run adapter-balances synthetix optimism 0xd09583bbf77d0da34cd02612fe41af4ae37ebc95`
`pnpm run adapter-balances synthetix ethereum 0xdcabc755fb10931e6d8059113f762cd8a6813deb`
`pnpm run adapter synthetix ethereum 0xb9fc7a5e4147e013e20348d94ad2badadf4d2045`

Feat: Adapter, SNX (Ethereum-Optimism)

---

src/adapters/curve-dex/common/balance.ts

Small-Fix decimals for some underlyings were too low -> blacklist logic to prevent these exceptions
`pnpm run adapter-balances curve-dex ethereum 0x50664ede715e131f584d3e7eaabd7818bb20a068`
==================================================================================
`pnpm run adapter-balances curve-dex ethereum 0x7a16ff8270133f063aab6c9977183d9e72835428`

Fix: Curve  

---

src/adapters/aave-v2/common/rewards.ts

Fix Aave_v2 rewards on ethereum with `1 stkAave = 1Aave`
`pnpm run adapter-balances aave-v2 ethereum 0x50664ede715e131f584d3e7eaabd7818bb20a068`

Fix: Aave_v2 rewards (stkAave)

---

.vscode/launch.json
src/adapters/fractional-art/ethereum/index.ts
src/adapters/fractional-art/ethereum/vault.ts
src/adapters/fractional-art/index.ts
src/adapters/index.ts

Add Fractional-art adapter, (nft stake)
`pnpm run adapterfractional-art ethereum 0x50664ede715e131f584d3e7eaabd7818bb20a068`
`pnpm run adapter-balances fractional-art ethereum 0x5dc58f812b2e244daba2fabd33f399cd699d7ddc`

Feat: Adapter, Fractional-art

---

.vscode/launch.json
src/adapters/ankr/avalanche/index.ts
src/adapters/ankr/bsc/index.ts
src/adapters/ankr/common/balance.ts
src/adapters/ankr/ethereum/balance.ts
src/adapters/ankr/ethereum/index.ts
src/adapters/ankr/fantom/index.ts
src/adapters/ankr/index.ts
src/adapters/index.ts

Add Ankr Adapter
`pnpm run adapter-balances ankr ethereum 0x99534ef705df1fff4e4bd7bbaaf9b0dff038ebfe`
`pnpm run adapter-balances ankr ethereum 0xf27c965945a7c06fb63be1428bdb84dda50edc6c`
`pnpm run adapter-balances ankr ethereum 0x8cbee4b481112e44b92817b26f96918221489485`
`pnpm run adapter-balances ankr ethereum 0xf78d83b4b2228ffeb33a0f999654a52c89c1bc1d`
`pnpm run adapter ankr bsc 0x25b21472c073095bebc681001cbf165f849eee5e`
`pnpm run adapter-balances ankr avalanche 0x542dd5f38fcb3aab28d6418cf3e1d36329a79ac7`
`pnpm run adapter-balances ankr fantom 0x20dd72ed959b6147912c2e529f0a0c651c33c9ce`

Feat: Adapter, Ankr

---

src/adapters/aura/ethereum/index.ts
src/adapters/convex-finance/ethereum/index.ts
src/lib/lock.ts

There was an invalid Date on Convex.
Added a condition allowing the abi to be more flexible
`pnpm run adapter-balances convex-finance ethereum 0xa0f75491720835b36edc92d06ddc468d201e9b73`

Fix: Lib Lock

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/pods/ethereum/balance.ts
src/adapters/pods/ethereum/index.ts
src/adapters/pods/index.ts

Add Pods adapter on Ethereum
`pnpm run adapter-balances pods ethereum 0x488fb8371ad8b20e39e3ce99d267e26c171b7d10`
`pnpm run adapter pods ethereum 0x7bfee91193d9df2ac0bfe90191d40f23c773c060`

Feat: Adapter, Pods

---

.vscode/launch.json
src/adapters/aave-v2/avalanche/index.ts
src/adapters/aave-v2/ethereum/index.ts
src/adapters/aave-v2/polygon/index.ts
src/adapters/aave-v3/arbitrum/index.ts
src/adapters/aave-v3/avalanche/index.ts
src/adapters/aave-v3/fantom/index.ts
src/adapters/aave-v3/optimism/index.ts
src/adapters/aave-v3/polygon/index.ts
src/adapters/index.ts
src/adapters/spark/ethereum/contract.ts
src/adapters/spark/ethereum/index.ts
src/adapters/spark/index.ts

Add Spark Adapter
> (There were small differences in the abi preventing us from reusing the function to retrieve the contracts)
> Using promises to retrieve healthfactors on Aave to launch calls in parallel
`pnpm run adapter spark ethereum 0xfe13988736d95d052c2e45e5b4e1ef2e2750b7f4`
`pnpm run adapter spark ethereum 0x9026a229b535ecf0162dfe48fdeb3c75f7b2a7ae`

Feat: Adapter, Spark (Aave fork)

---

.vscode/launch.json
src/adapters/elephant-money/bsc/farmer.ts
src/adapters/elephant-money/bsc/index.ts
src/adapters/elephant-money/bsc/stake.ts
src/adapters/elephant-money/index.ts
src/adapters/index.ts

Add Elephant-money adapter on bsc chain
/!\ - Unfortunately, price of TRUNK token is not supported by Defillama API - /!\
`pnpm run adapter-balances elephant-money bsc scan 0xcb71eb21f53a2f4de0f26dc90518df10be13d1ec`

Feat: Adapter, Elephant-money

---

src/adapters/balancer/common/balance.ts

> Fixed Aura underlyings, sometimes there were still lpTokens in the underlyings which tended to add abnormal amounts
`pnpm run adapter-balances aura ethereum 0x35e3564c86bc0b5548a3be3a9a1e71eb1455fad2`
`pnpm run adapter-balances aura ethereum 0x35e3564c86bc0b5548a3be3a9a1e71eb1455fad2`

Fix: Aura underlyings using Balancer logic

---

src/adapters/aave-v3/arbitrum/index.ts
src/adapters/aave-v3/avalanche/index.ts
src/adapters/aave-v3/common/lending.ts
src/adapters/aave-v3/fantom/index.ts
src/adapters/aave-v3/optimism/index.ts
src/adapters/aave-v3/polygon/index.ts

AVALANCHE
`pnpm run adapter aave-v3 avalanche 0x5a2d0e3d6f862ee155f52ab65b6b22e1d80f5716`
BEFORE
AFTER
POLYGON
`pnpm run adapter aave-v3 polygon 0x31e411356d89f8a4149149bbd7beb7d12f863670`
BEFORE
AFTER

Fix: Incentive rewards on Aave

---

src/adapters/aura/ethereum/balance.ts

> Aura rewards were negative and wrong since we switch BN to BigInt
`pnpm run adapter aura ethereum 0x9026a229b535ecf0162dfe48fdeb3c75f7b2a7ae`
BEFORE
AFTER
dAPP values

Fix: Aura rewards were negative and wrong since we switch BN to BigInt

---

src/adapters/lybra-finance/ethereum/vest.ts

`pnpm run adapter-balances lybra-finance ethereum 0x9026a229b535ecf0162dfe48fdeb3c75f7b2a7ae`
BEFORE
AFTER

Fix: LBR asset

---

src/adapters/ether.fi/ethereum/index.ts
src/adapters/ether.fi/ethereum/stake.ts

Ether.fi now fit with more liquid eth staking (it was working only with WETH until now)
`pnpm run adapter-balances ether.fi ethereum 0x9026a229b535ecf0162dfe48fdeb3c75f7b2a7ae`
`pnpm run adapter-balances ether.fi ethereum 0xcfd727653c3d5a1b943f675781d3245b884f1d34`
`pnpm run adapter-balances ether.fi ethereum 0x857ab110153ad57240ab920e93bfb549c045af55`

Fix: Adapter, Ether.fi

---

src/adapters/1inch-network/common/locker.ts
src/adapters/1inch-network/common/reward.ts
src/adapters/1inch-network/ethereum/index.ts

Added a missing function to find the rewards when locked on 1Inch on ethereum
`pnpm run adapter-balances 1inch-network ethereum 0xf848e69ea6e206e6e8f2fbfc46ddd27c73907979`
`pnpm run adapter-balances 1inch-network ethereum 0xc948eb5205bde3e18cac4969d6ad3a56ba7b2347`

Feat: Adapter 1Inch-Network (rewards)

---

src/adapters/aura/ethereum/balance.ts
src/adapters/aura/ethereum/pool.ts
src/adapters/balancer/common/balance.ts
src/lib/price.ts

Add a fix on balance filter now allowing to display rewards left by a user if he has ever withdrawn his principal
`pnpm run adapter aura ethereum 0x9026a229b535ecf0162dfe48fdeb3c75f7b2a7ae`
BEFORE
NOW
AURA EXTRA REWARDS
_(LDO on this test address)_

Fix:  Balance filter + Aura extra rewards

---

src/adapters/uniswap-v3/common/pools.ts

Small fix on uniswap-v3 since there may be an underlying at 0 if user is out of range
pnpm run adapter-balances uniswap-v3 ethereum 0x26fcbd3afebbe28d0a8684f790c48368d21665b5
BEFORE
AFTER

Fix: Adapter Uniswap-v3

---

.vscode/launch.json
src/adapters/exactly/common/balance.ts
src/adapters/exactly/common/market.ts
src/adapters/exactly/ethereum/index.ts
src/adapters/exactly/index.ts
src/adapters/exactly/optimism/index.ts
src/adapters/index.ts

Add Exactly adapter on both Ethereum + Optimism
`pnpm run adapter exactly optimism 0xb5a9621b0397bfc5b45896cae5998b6111bcdce6`
`pnpm run adapter exactly optimism 0xf567361ff0bcdcad1252c8e2fb8e5d4a9bb4e266`
`pnpm run adapter exactly ethereum 0x8a6134ecba73d51f64794f93c6d0c057893d328d`
`pnpm run adapter exactly ethereum 0x5d1124fb77c539ec92e3ef853053bbce1e98271b`

feat: Adapter Exactly

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/morpho-aave/ethereum/balances.ts
src/adapters/morpho-aave/ethereum/contract.ts
src/adapters/morpho-aave/ethereum/index.ts
src/adapters/morpho-aavev3/ethereum/balance.ts
src/adapters/morpho-aavev3/ethereum/contract.ts
src/adapters/morpho-aavev3/ethereum/index.ts
src/adapters/morpho-aavev3/index.ts

Added Morpho-Aave v3 logic based on @pragneshmangukiya's work with some refactorings #680 
`pnpm run adapter morpho-aave ethereum 0xd0b8dfcf9da999db981a60a8da6584e8e52b757c`

feat: Adapter, MorphoAave

---

.env.example
.github/workflows/refresh-r2.yml
docs/contributing.md
environment.ts
src/db/yields.ts
test/routes.sh

As part of the discussion related to https://github.com/llamafolio/llamafolio-api/issues/626, https://yields.llama.fi/poolsOld is a large payload so understandably takes time to retrieve. Storing it in R2 allows for radically fast read performance.

feat: store yield pools in r2

---

src/adapters/convex-finance/ethereum/index.ts
src/adapters/convex-finance/ethereum/stake.ts

Add missing 3CRV rewards on crvCVX stake
`pnpm run adapter-balances convex-finance ethereum 0xf929122994e177079c924631ba13fb280f5cd1f9`

feat: Adapter Convex-Finance

---

src/adapters/convex-finance/ethereum/index.ts
src/adapters/convex-finance/ethereum/stake.ts

3CRV address was not correct in crvCVXRewards which prevented the display of logo and price on Llamafolio

fix: Adapter Convex-Finance

---

src/adapters/gravita-protocol/ethereum/index.ts
src/adapters/gravita-protocol/ethereum/stake.ts

Stake logic was not functional since rewards calls were reverted due to an error in the abi used.
`pnpm run adapter-balances gravita-protocol ethereum 0x3ec6732676db7996c1b34e64b0503f941025cb63`
BEFORE
NOW

fix: Adapter Gravita-Protocol

---

src/adapters/radiant-v2/bsc/index.ts
src/adapters/radiant-v2/bsc/multifee.ts
src/adapters/radiant-v2/index.ts

`pnpm run adapter-balances radiant-v2 bsc 0x59a661f1c909ca13ba3e9114bfdd81e5a420705d`

feat: Adapter, Radiant-v2 on BSC

---

src/adapters/morphex/fantom/balance.ts

There was a wrong call as we can see on this SS
> abi call function was  `TotalSupply` instead of `Claimable` for `contract.rewarder` (address)
`pnpm run adapter-balances morphex fantom 0x19145b49fd5e4c345822a4a83fe5543c5bbb785c`

fix: Adapter, Morphex

---

.vscode/settings.json
serverless.yml
src/handlers/getNFTs.ts
src/handlers/getNFTsHistory.ts
src/lib/fetcher.ts
src/lib/nft/class.ts
src/lib/nft/index.ts
src/lib/nft/quick-node.ts
src/lib/nft/reservoir.ts
src/lib/nft/sequence.ts
src/lib/type.ts
tsconfig.json

https://github.com/llamafolio/llamafolio-api/issues/736

nft token trade history

---

.vscode/launch.json
src/adapters/colony/avalanche/balance.ts
src/adapters/colony/avalanche/index.ts
src/adapters/colony/index.ts
src/adapters/index.ts

`pnpm run adapter colony avalanche 0x248587cca737e313f5b15548c93cb5624a616729`
`pnpm run adapter colony avalanche 0x2f28cc3f13a303da007f49d615479fe0265326c5`

feat: Adapter, Colony

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/synclub-staked-bnb/bsc/index.ts
src/adapters/synclub-staked-bnb/bsc/stake.ts
src/adapters/synclub-staked-bnb/index.ts

`pnpm run adapter synclub-staked-bnb bsc 0x1adb950d8bb3da4be104211d5ab038628e477fe6`

feat: Adapter, Synclub-staked-bnb

---

src/adapters/benqi-lending/avalanche/index.ts
src/lib/compound/v2/lending.ts

fix qiAvax
`pnpm run adapter benqi-lending avalanche 0x52e4ddae8b19d98cb878e0afaa418d9060944c35`

feat: adapter, benqi-lending

---

src/adapters/stargate/base/index.ts
src/adapters/stargate/common/contract.ts
src/adapters/stargate/index.ts

> Fix an issue for chains using ETH as gas, Stargate transform ETH into SGETH to distinguish them, but we could not recover the price by Defillama, so i replaced SGETH with WETH for these chains
`pnpm run adapter stargate optimism 0x4dea9e918c6289a52cd469cac652727b7b412cd2`
BEFORE FIX
AFTER FIX
BASE
_LP_
`pnpm run adapter stargate base 0x81eab64e630c4a2e3e849268a6b64cb76d1c8109`
_FARM_
`pnpm run adapter stargate base 0x816a0e727027cf5a15bed81d5b580bde829bd33b`

feat: Fix Stargate (SGETH to WETH) + add Base

---

src/adapters/aave-v3/base/index.ts
src/adapters/aave-v3/index.ts

`pnpm run adapter aave-v3 base 0xe193932b92ce312a214b9c1afd402fd977422dea`

feat: Adapter, Aave-v3, base

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/ondo-finance/ethereum/balance.ts
src/adapters/ondo-finance/ethereum/index.ts
src/adapters/ondo-finance/index.ts

> Add `Ondo-finance` on `ethereum`
`pnpm run adapter-balances ondo-finance ethereum 0x1dd7950c266fb1be96180a8fdb0591f70200e018`

feat: Adapter, ondo-finance

---

src/adapters/curve-dex/ethereum/lpBalance.ts
src/adapters/curve-dex/ethereum/pools.ts

> Add handling error
> Fix missing pools --> We were filtering the pools according to the responses to different calls including gaugeType and poolName which led to losing pools

fix: curve-dex on ethereum

---

src/adapters/inverse-finance/ethereum/index.ts

> Add missing contracts on Inverse-Finance
`pnpm run adapter inverse-finance ethereum 0x7a16ff8270133f063aab6c9977183d9e72835428`

Feat: Adapter, Inverse-finance contracts

---

src/adapters/silo-finance/ethereum/index.ts

`pnpm run adapter-balances silo-finance ethereum 0x7a16ff8270133f063aab6c9977183d9e72835428`

feat: Adapter, silo-finance, add missing contract

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/vesper/avalanche/index.ts
src/adapters/vesper/common/balance.ts
src/adapters/vesper/common/pool.ts
src/adapters/vesper/ethereum/index.ts
src/adapters/vesper/index.ts
src/adapters/vesper/optimism/index.ts
src/adapters/vesper/polygon/index.ts

> Add Vesper adapter on several chains
`npm run adapter vesper ethereum 0x698137c473bc1f0ea9b85ade45caf64ef2df48d6`
`npm run adapter vesper ethereum 0xc17cbb210b2dd44bb07d55212c6de6961404ec94`
`npm run adapter vesper optimism 0x4fd49322ccc93078baf8011b70abc58ffe1a181b`
`npm run adapter vesper polygon 0x041550d216b0eec58d2cbc34798b26ba2c0f2b37`
`npm run adapter vesper avalanche 0xdee08599414228dc21e8f0b8b87f674162e82e0a`

feat: Adapter, Vesper

---

src/db/balances.ts
src/handlers/getBalances.ts
src/handlers/updateBalances.ts

This denormalized structure has many advantages compared to the previous one:
- grouping balances per adapter / per chain / per day / per user ensures that balances get correctly replaced by the ReplacingMergeTree engine if we make changes to an adapter
- ensures we're only storing daily balances for each user (not xxx balances if we update it  many times a day)
- easily access latest balances
- easily access historical balances and make it easier to run backfill jobs per adapter

feat: aggregate balances by adapter

---

src/adapters/lido/ethereum/index.ts
src/adapters/lido/ethereum/unstake.ts

`pnpm run adapter-balances lido ethereum 0x171c53d55b1bcb725f660677d9e8bad7fd084282`

feat: Update Lido, pending withdraw

---

src/adapters/stakedao/common/balance.ts
src/adapters/stakedao/ethereum/index.ts

`pnpm run adapter-balances stakedao ethereum 0x7a16ff8270133f063aab6c9977183d9e72835428`

small fix on stakedao since balancer had issues on its contracts

---

package.json
src/handlers/getBalancesTokens.ts
src/lib/balance.ts
src/lib/price.ts

fix few edge cases and reuse function:
- return balances if failed to fetch price of token but underlyings worked correctly
- return balances if unstaked tokens but still have some unclaimed rewards

fix: balances sanitize consider underlyings and rewards

---

src/adapters/radiant-v2/arbitrum/multifee.ts

> There was an issue with underlyings of radiant-v2 on arbitrum which prevented the function from returning values

fix lock balances

---

src/lib/balance.ts

It's possible for LP values to have underlyings with amount at 0 (ex: uniswap-v3), we should not assume underlyings to have a special value (but a sane one to avoid massive balances)

fix: balances underlyings value can be 0

---

src/adapters/stargate/ethereum/vest.ts

> There was an issue with `bigint * number` types

fix :Adapter, Stargate vesting ethereum

---

src/lib/balance.ts
src/lib/fmt.ts

force using UTC date and compare Unix timestamps in seconds instead of JS milliseconds

fix: stale balances timestamp

---

src/adapters/yearn-finance/common/balance.ts

`pnpm run adapter-balances yearn-finance ethereum 0xc64844d9b3db280a6e46c1431e2229cd62dd2d69`
BEFORE
NOW

Feat:Adapter,Yearn-Finance

---

.vscode/launch.json
src/adapters/channels-finance/arbitrum/index.ts
src/adapters/channels-finance/bsc/index.ts
src/adapters/channels-finance/index.ts
src/adapters/index.ts

`pnpm run adapter-balances channels-finance bsc 0xfc8fe5ced7ce60bffbadadffce2989e4b4c68ff4`
`pnpm run adapter-balances channels-finance bsc 0x5eac4a9c2fb481e016a526b4fc3aa8205f72ddb9`
`pnpm run adapter-balances channels-finance arbitrum 0xf4b93a76bfedbaa5dd58c37c438bde519e881b37`

Feat: Adapter, Channels-Finance (compound forks)

---

src/adapters/compound-v3/arbitrum/index.ts

Circle has released a native USDC version on Arbitrum (read [www.circle.com](https://www.circle.com/blog/arbitrum-usdc-now-available)) and CompoundV3 now supports both tokens;
USDC.e (Bridged) TVL: $5.82m
USDC (Native) TVL: $30.53m
As per the new version of USDC has around ~5x the TVL, this lead me to make the pull-request as it's TVL is much higher, and users are most-likely to be earning/borrowing/... from this new pool.
I had to fiddle a little bit with the naming because both pools have the same ticker; let me know your feedback and I'm happy to address it.
> Documentation: https://docs.compound.finance/#networks
> Data: https://app.compound.finance/markets

feat(compound-v3): Support Native USDC pool

---

src/lib/providers/viem.ts

Simplify type inference for `viem` PublicClient configuration types

chore: Simplify type

---

src/adapters/compound-v3/arbitrum/index.ts
src/adapters/compound-v3/base/index.ts
src/adapters/compound-v3/common/asset.ts
src/adapters/compound-v3/common/balance.ts
src/adapters/compound-v3/ethereum/index.ts
src/adapters/compound-v3/polygon/index.ts

> Fix interactions issues, Compound-v3 balances should now display correctly on Llamafolio
` pnpm run adapter-balances compound-v3 arbitrum 0x17ae0a6be2e97b384165626db2569729d5006640`
`pnpm run adapter-balances compound-v3 base 0xa31c0e3cc5d884375eb9f7aeb3e2bfe8943bc00e`

Fix, Compound_v3 Interactions issues

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/yama-finance/arbitrum/CDP.ts
src/adapters/yama-finance/arbitrum/balance.ts
src/adapters/yama-finance/arbitrum/index.ts
src/adapters/yama-finance/index.ts

Add [Yama Finance](https://defillama.com/protocol/yama-finance) adapter. This only takes care of Arbitrum (Lend) which has the highest TVL, instead of Polygon that seems abandoned with less than $15 TVL.
`pnpm run adapter yama-finance arbitrum 0x7bfee91193d9df2ac0bfe90191d40f23c773c060`
> Note: I cross-checked the results and data with DeBank at https://debank.com/profile/0x7bfee91193d9df2ac0bfe90191d40f23c773c060?chain=arb

feat: Adapter, Yama Finance

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/mev-protocol/ethereum/balance.ts
src/adapters/mev-protocol/ethereum/index.ts
src/adapters/mev-protocol/index.ts
src/adapters/vesper/common/balance.ts

`pnpm run adapter mev-protocol ethereum 0x36cc7b13029b5dee4034745fb4f24034f3f2ffc6`

Feat:Adapter,Mev-protocol

---

.vscode/launch.json
src/adapters/blast/ethereum/balance.ts
src/adapters/blast/ethereum/index.ts
src/adapters/blast/index.ts
src/adapters/index.ts

`pnpm run adapter blast ethereum 0x27c79a01878962ce0b6126af6e184c06d36c8f37`

Feat:Adapter,Blast

---

pnpm-lock.yaml

Last commit to `master` (4171808dcbdc815b2b908e4902da17fd6bbab5e8) broke the CI and some builds, due to bumping a dependency without installing it resulting in errors when trying to install with `--frozen-lockfile`; this PR solves it
`ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up to date with package.json`

fix: Package lock

---

src/adapters/ether.fi/ethereum/index.ts
src/adapters/ether.fi/ethereum/node.ts
src/adapters/ether.fi/ethereum/stake.ts

`pnpm run adapter-balances ether.fi ethereum 0xccf343eef0c5f2590ee30efc9f564b33aeb3c7e6`

Update:Adapter,Ether.fi, nodeStaking + weETH + eETH

---

.vscode/launch.json
src/adapters/asymmetry-finance/ethereum/index.ts
src/adapters/asymmetry-finance/ethereum/stake.ts
src/adapters/asymmetry-finance/index.ts
src/adapters/index.ts

`pnpm run adapter asymmetry-finance ethereum 0xf7b10d603907658f690da534e9b7dbc4dab3e2d6`

Feat:Adapter,Asymmetry-Finance,Ethereum

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/mantle-staked-eth/ethereum/index.ts
src/adapters/mantle-staked-eth/index.ts

` pnpm run adapter mantle-staked-eth ethereum 0x78605df79524164911c144801f41e9811b7db73d`

feat:Adapter,mETH

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/kelp-dao/ethereum/balance.ts
src/adapters/kelp-dao/ethereum/index.ts
src/adapters/kelp-dao/index.ts

`pnpm run adapter-balances kelp-dao ethereum 0xbcb4c8386c097589e7825aaeb9e7c6295835f1d6`

Feat:Adapter,KelpDao,Ethereum (LST)

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/syncus/ethereum/index.ts
src/adapters/syncus/index.ts

`pnpm run adapter-balances syncus ethereum 0x96b1f517912e8b7269566079266d148c2c9607c3`

Feat:Adapter,Syncus,ethereum

---

.vscode/launch.json
src/adapters/fyde-protocol/ethereum/balance.ts
src/adapters/fyde-protocol/ethereum/index.ts
src/adapters/fyde-protocol/index.ts
src/adapters/index.ts

`pnpm run adapter fyde-protocol ethereum 0x4ea2928b5fbca400b4ba3721d55f2a2865c66476`

Feat:Adapter,Fyde,Ethereum

---

.vscode/launch.json
src/adapters/bedrock-unieth/ethereum/balance.ts
src/adapters/bedrock-unieth/ethereum/index.ts
src/adapters/bedrock-unieth/index.ts
src/adapters/index.ts

`pnpm run adapter bedrock-unieth ethereum 0xe16445ab6b7ea70380ce2d0c672cd7a8cd7a16f0`

Feat:Adapter,Bedrock,Ethereum

---

.vscode/launch.json
src/adapters/genesis-lrt/ethereum/balance.ts
src/adapters/genesis-lrt/ethereum/index.ts
src/adapters/genesis-lrt/index.ts
src/adapters/index.ts

`pnpm run adapter genesis-lrt ethereum 0x7bfee91193d9df2ac0bfe90191d40f23c773c060`

Feat:Adapter,Genesis-LRT,Ethereum

---

scripts/test-multicall.ts
src/lib/multicall.ts

fix: https://github.com/llamafolio/llamafolio-api/issues/1261

fix: fallback to eth_call if Multicall not deployed at block

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/wagmi/ethereum/index.ts
src/adapters/wagmi/fantom/index.ts
src/adapters/wagmi/index.ts
src/adapters/wagmi/zksync-era/index.ts

`pnpm run adapter wagmi ethereum 0x6f16e40e48d47a5d9b506cf7ca1e0126cd2d4dd6`

feat:Adapter,Wagmi,dexes

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/unicly/ethereum/index.ts
src/adapters/unicly/index.ts

`pnpm run adapter unicly ethereum 0x279d287c8e9ac9c2863b4c73a650877a94928626`

feat:Adapter,Unicly,ethereum,dexes

---

.vscode/launch.json
src/adapters/9inch/ethereum/index.ts
src/adapters/9inch/index.ts
src/adapters/index.ts

`pnpm run adapter 9inch ethereum 0x3fefd06828689252a69207718985b9a78350561f`

feat:Adapter,9inch,ethereum

---

.vscode/launch.json
src/adapters/index.ts
src/adapters/vector-reserve/ethereum/balance.ts
src/adapters/vector-reserve/ethereum/index.ts
src/adapters/vector-reserve/index.ts

`pnpm run adapter vector-reserve ethereum 0xfdc28cd1bfebf3033870c0344b4e0bee639be9b1`
`pnpm run adapter vector-reserve ethereum 0xba12222222228d8ba445958a75a0704d566bf2c8`

feat:Adapter,Vector-reserve,ethereum

---

.vscode/launch.json
src/adapters/blueprint/ethereum/index.ts
src/adapters/blueprint/index.ts
src/adapters/index.ts

`pnpm run adapter blueprint ethereum 0x13d079048a83dd7524aa19c9528a7eeac22fa638`

feat:Adapter,Blueprint,ethereum

---

src/adapters/uwu-lend/ethereum/index.ts
src/adapters/uwu-lend/ethereum/lending.ts
src/adapters/uwu-lend/ethereum/multifee.ts

`pnpm run adapter uwu-lend ethereum 0x7bfee91193d9df2ac0bfe90191d40f23c773c060`

fix, Uwu-lend

---

src/adapters/ether.fi/ethereum/index.ts
src/lib/slack.ts

> the current way of retrieving node balances requires querying the smart contract for all existing tokenIds (10k+) which fails, comment while waiting to find a way to retrieve the tokenId of each user

Ether.fi fix

---

src/adapters/gains-network/arbitrum/index.ts
src/adapters/gains-network/common/stake.ts
src/adapters/gains-network/polygon/index.ts
src/handlers/getBalances.ts

` pnpm run adapter-balances gains-network polygon 0xe0f715e6b011cb3aa67e78ed2d3e74f1f31049c4`

Gains network fix

---

src/adapters/aave-v3/common/stake.ts
src/adapters/aave-v3/ethereum/index.ts

`pnpm run adapter-balances aave-v3 ethereum 0xb72ed8401892466ea8af528c1af1d0524bc5e105`

update Aave-v3 ethereum, add stake

---

src/adapters/across/ethereum/index.ts
src/adapters/across/ethereum/v2/balance.ts

`pnpm run adapter-balances across ethereum 0xb72ed8401892466ea8af528c1af1d0524bc5e105`

fix across (missing reward + using share instead of assetBalance)

---

src/handlers/updateBalances.ts
src/lib/adapter.ts

add timeout for each adapter#getBalances during an update to make sure one adapter doesn't timeout the entire Lambda

fix: updateBalances handler adapter timeout

---

.vscode/launch.json
src/adapters/ethena/ethereum/balance.ts
src/adapters/ethena/ethereum/index.ts
src/adapters/ethena/index.ts
src/adapters/index.ts

`pnpm run adapter ethena ethereum 0x7bc0146115c29168c9ca25086e42c2b50c3c8768`

feat:Adapter,Ethena,Ethereum

---

.vscode/launch.json
src/adapters/ft33-dao/base/index.ts
src/adapters/ft33-dao/index.ts
src/adapters/index.ts

`pnpm run adapter ft33-dao base 0x7bfee91193d9df2ac0bfe90191d40f23c773c060`

feat:Adapter,Ft33-dao

---

src/adapters/matrix-farm/arbitrum/index.ts
src/adapters/matrix-farm/base/index.ts
src/adapters/matrix-farm/common/balance.ts
src/adapters/matrix-farm/common/vault.ts
src/adapters/matrix-farm/fantom/index.ts
src/adapters/matrix-farm/index.ts
src/adapters/matrix-farm/optimism/index.ts

`pnpm run adapter matrix-farm optimism 0x6c529ce2bdd778e8c9d36c75a434e626a583caa9`
`pnpm run adapter matrix-farm base 0xeb1e9b68ff7450a29dd7b0aefe5839546923ce8a`

feat:Adapter,MatrixFarm

---

.vscode/launch.json
src/adapters/definitive.fi/arbitrum/index.ts
src/adapters/definitive.fi/avalanche/index.ts
src/adapters/definitive.fi/base/index.ts
src/adapters/definitive.fi/common/balance.ts
src/adapters/definitive.fi/common/pool.ts
src/adapters/definitive.fi/ethereum/index.ts
src/adapters/definitive.fi/index.ts
src/adapters/definitive.fi/optimism/index.ts
src/adapters/definitive.fi/polygon/index.ts
src/adapters/index.ts

` pnpm run adapter-balances definitive.fi ethereum 0xa3aaf59806b4dd3a08769d07c93bf62470b8db02`

feat:Adapter,Definitive

---

.vscode/launch.json
src/adapters/davos-protocol/arbitrum/index.ts
src/adapters/davos-protocol/common/balance.ts
src/adapters/davos-protocol/common/vault.ts
src/adapters/davos-protocol/ethereum/index.ts
src/adapters/davos-protocol/index.ts
src/adapters/davos-protocol/optimism/index.ts
src/adapters/davos-protocol/polygon/index.ts
src/adapters/index.ts

`pnpm run adapter-balances davos-protocol optimism 0x29b4d3065ecf5a8ad740ea72bd23570323308238`

feat:Adapter,Davos

---

src/db/balances-ddb.ts
src/db/balances.ts
src/lib/balance.ts
src/lib/fmt.ts

fix: safe parse decimals
